const audioSermons = [
  {
    audNum: 1,
    title: "Be Unified",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "November-5-1970",
  },
  {
    audNum: 2,
    title: "A Chosen Spot (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1973",
    date: "January-7-1973",
  },
  {
    audNum: 3,
    title: "A Chosen Spot (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1973",
    date: "January-7-1973",
  },
  {
    audNum: 4,
    title: "A Cross To Bear",
    type: "mp3",
    audioUrl:'',
    year: "1964",
    date: "April-19-1964",
  },
  {
    audNum: 5,
    title: "A Drink From The Well Of Bethleham",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "December-21-1969",
  },
  {
    audNum: 6,
    title: "A Dwelling Place For God",
    type: "mp3",
    audioUrl:'',
    year: "1964",
    date: "October-18-1964",
  },
  {
    audNum: 7,
    title: "A Purpose To Stand (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "September-28-1969",
  },
  {
    audNum: 8,
    title: "A Purpose To Stand (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "September-28-1969",
  },
  {
    audNum: 9,
    title: "A Resting Place For The Ark (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "December-8-1968",
  },
  {
    audNum: 10,
    title: "A Resting Place For The Ark (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "December-8-1968",
  },
  {
    audNum: 11,
    title: "A Spiritual Race",
    type: "mp3",
    audioUrl:'',
    year: "1964",
    date: "October-11-1964",
  },
  {
    audNum: 12,
    title: "Abel's Sacrifice",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "March-9-1969",
  },
  {
    audNum: 13,
    title: "Abraham And Lot (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "August-11-1968",
  },
  {
    audNum: 14,
    title: "Abraham And Lot (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "August-11-1968",
  },
  {
    audNum: 15,
    title: "Abraham Royal Seed In The Journey (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "August-18-1968",
  },
  {
    audNum: 16,
    title: "Abraham Royal Seed In The Journey (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "August-18-1968",
  },
  {
    audNum: 17,
    title: "All Willing To Pay The Price (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "October-4-1970",
  },
  {
    audNum: 18,
    title: "All Willing To Pay The Price (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "October-4-1970",
  },
  {
    audNum: 19,
    title: "An Open Door",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "May-19-1968",
  },
  {
    audNum: 20,
    title: "An Open Door (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "May-16-1971",
  },
  {
    audNum: 21,
    title: "An Open Door (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "May-16-1971",
  },
  {
    audNum: 22,
    title: "An Uncertain Sound",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "October-29-1970",
  },
  {
    audNum: 23,
    title: "And Israel Abode At Kadesh",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "August-14-1969",
  },
  {
    audNum: 24,
    title: "Apostasy (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "March-23-1969",
  },
  {
    audNum: 25,
    title: "Apostasy (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "March-23-1969",
  },
  {
    audNum: 26,
    title: "Attraction In The Bride (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "November-9-1969",
  },
  {
    audNum: 27,
    title: "Attraction In The Bride (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "November-9-1969",
  },
  {
    audNum: 28,
    title: "Awakening Gods Children",
    type: "mp3",
    audioUrl:'',
    year: "1973",
    date: "April-29-1973",
  },
  {
    audNum: 29,
    title: "Baptism Of The Holy Ghost In Relation To The New Birth (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "August-29-1971",
  },
  {
    audNum: 30,
    title: "Baptism Of The Holy Ghost In Relation To The New Birth (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "August-29-1971",
  },
  {
    audNum: 31,
    title: "Beatitudes",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "October-1-1972",
  },
  {
    audNum: 32,
    title: "Beginning Of Sorrows (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "October-11-1970",
  },
  {
    audNum: 33,
    title: "Beginning Of Sorrows (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "October-11-1970",
  },
  {
    audNum: 34,
    title: "Being Subject",
    type: "mp3",
    audioUrl:'',
    year: "1965",
    date: "April-14-1965",
  },
  {
    audNum: 35,
    title: "Believing In Christ",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "January-17-1971",
  },
  {
    audNum: 36,
    title: "Bible Prophecy #1 (Rev. 13)",
    type: "mp3",
    audioUrl:'',
    year: "1973",
    date: "May-27-1973",
  },
  {
    audNum: 37,
    title: "Bible Prophecy #2 (Rev.)",
    type: "mp3",
    audioUrl:'',
    year: "1973",
    date: "May-27-1973",
  },
  {
    audNum: 38,
    title: "Bible Prophecy #3 (Red Dragon)",
    type: "mp3",
    audioUrl:'',
    year: "1973",
    date: "June-3-1973",
  },
  {
    audNum: 39,
    title: "Bible Prophecy #4 (70 WK)",
    type: "mp3",
    audioUrl:'',
    year: "1973",
    date: "June-10-1973",
  },
  {
    audNum: 40,
    title: "Bible Prophecy #5 (Two Witnesses)",
    type: "mp3",
    audioUrl:'',
    year: "1973",
    date: "June-10-1973",
  },
  {
    audNum: 41,
    title: "Bible Prophecy #6 (USA)",
    type: "mp3",
    audioUrl:'',
    year: "1973",
    date: "July-11-1973",
  },
  {
    audNum: 42,
    title: "Birthright",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "February-25-1968",
  },
  {
    audNum: 43,
    title: "Blind Laodicea (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "December-8-1968",
  },
  {
    audNum: 44,
    title: "Blind Laodicea (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "December-8-1968",
  },
  {
    audNum: 45,
    title: "Bride In The Spirit (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "June-20-1971",
  },
  {
    audNum: 46,
    title: "Bride In The Spirit (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "June-20-1971",
  },
  {
    audNum: 47,
    title: "Bro. Bob's Jamaica Trip (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "March-6-1969",
  },
  {
    audNum: 48,
    title: "Bro. Bob's Jamaica Trip (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "March-6-1969",
  },
  {
    audNum: 49,
    title: "Bro. Bob's-Robert Lee Lambert's Testimony (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "January-26-1969",
  },
  {
    audNum: 50,
    title: "Bro. Bob's-Robert Lee Lambert's Testimony (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "January-26-1969",
  },
  {
    audNum: 51,
    title: "Bro. Branham's Heavenly Vision",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "August-6-1970",
  },
  {
    audNum: 52,
    title: "Bro. Robert Lambert's Funeral",
    type: "mp3",
    audioUrl:'',
    year: "1973",
    date: "August-6-1973",
  },
  {
    audNum: 53,
    title: "Broken Fellowship",
    type: "mp3",
    audioUrl:'',
    year: "1967",
    date: "April-30-1967",
  },
  {
    audNum: 54,
    title: "Broken Fellowship (New York)",
    type: "mp3",
    audioUrl:'',
    year: "1964",
    date: "October-21-1964",
  },
  {
    audNum: 55,
    title: "Building On A Rock",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "May-14-1970",
  },
  {
    audNum: 56,
    title: "Building On Temple Of God (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "February-15-1970",
  },
  {
    audNum: 57,
    title: "Building On Temple Of God (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "February-15-1970",
  },
  {
    audNum: 58,
    title: "By Faith Noah (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "February-13-1972",
  },
  {
    audNum: 59,
    title: "By Faith Noah (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "February-13-1972",
  },
  {
    audNum: 60,
    title: "Calling Upon The Lord To Be Saved (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "September-12-1971",
  },
  {
    audNum: 61,
    title: "Calling Upon The Lord To Be Saved (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "September-12-1971",
  },
  {
    audNum: 62,
    title: "Cast Away Your Old Garment",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "February-2-1969",
  },
  {
    audNum: 63,
    title: "Cause Of Wrath Of GOD Today (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "September-19-1971",
  },
  {
    audNum: 64,
    title: "Cause Of Wrath Of GOD Today (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "September-19-1971",
  },
  {
    audNum: 65,
    title: "Children Of Disobedience (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "March-15-1970",
  },
  {
    audNum: 66,
    title: "Children Of Disobedience (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "March-15-1970",
  },
  {
    audNum: 67,
    title: "Church Age Book (Message To The Church)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "May-28-1970",
  },
  {
    audNum: 68,
    title: "Coming Of Christ",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "June-9-1968",
  },
  {
    audNum: 69,
    title: "Communion",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "April-9-1972",
  },
  {
    audNum: 70,
    title: "Compel Them To Come In",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "September-6-1970",
  },
  {
    audNum: 71,
    title: "Conditioning The Heart To Receive Rev.",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "September-24-1972",
  },
  {
    audNum: 72,
    title: "Contend (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "November-1-1970",
  },
  {
    audNum: 73,
    title: "Contend (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "November-1-1970",
  },
  {
    audNum: 74,
    title: "Contend For The Faith",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "February-13-1972",
  },
  {
    audNum: 75,
    title: "Crossing The Jordan",
    type: "mp3",
    audioUrl:'',
    year: "1967",
    date: "December-17-1967",
  },
  {
    audNum: 76,
    title: "Crucified In The Place Of A Skull",
    type: "mp3",
    audioUrl:'',
    year: "1973",
    date: "February-11-1973",
  },
  {
    audNum: 77,
    title: "David's First Love #1",
    type: "mp3",
    audioUrl:'',
    year: "1966",
    date: "December-25-1966",
  },
  {
    audNum: 78,
    title: "David's First Love #2",
    type: "mp3",
    audioUrl:'',
    year: "1966",
    date: "December-25-1966",
  },
  {
    audNum: 79,
    title: "David's Vision",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "September-24-1970",
  },
  {
    audNum: 80,
    title: "Deception Of Satan (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "December-26-1968",
  },
  {
    audNum: 81,
    title: "Deception Of Satan (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "December-26-1968",
  },
  {
    audNum: 82,
    title: "Deliverance From The Power Of Darkness",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "March-12-1972",
  },
  {
    audNum: 83,
    title: "Dreams And Seven Church Ages (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "October-9-1969",
  },
  {
    audNum: 84,
    title: "Dreams And Seven Church Ages (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "October-9-1969",
  },
  {
    audNum: 85,
    title: "Each Step I Take",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "January-28-1968",
  },
  {
    audNum: 86,
    title: "Eat, Drink & Be Merry",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "March-7-1971",
  },
  {
    audNum: 87,
    title: "Eating All The Lamb",
    type: "mp3",
    audioUrl:'',
    year: "1967",
    date: "July-5-1967",
  },
  {
    audNum: 88,
    title: "Elected Lady- Nuggets- Invisible Union (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1967",
    date: "November-30-1967",
  },
  {
    audNum: 89,
    title: "Elected Lady- Nuggets- Invisible Union (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1967",
    date: "November-30-1967",
  },
  {
    audNum: 90,
    title: "Election Of Abrahams Royal Seed & Jacob's Ladder",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "May-21-1972",
  },
  {
    audNum: 91,
    title: "Elisha",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "May-24-1970",
  },
  {
    audNum: 92,
    title: "Empty Vessels (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "October-19-1969",
  },
  {
    audNum: 93,
    title: "Empty Vessels (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "October-19-1969",
  },
  {
    audNum: 94,
    title: "Endtime Bride Of Christ About Her Father's Business",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "September-6-1970",
  },
  {
    audNum: 95,
    title: "Ephesians Parallels Joshua #1",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "October-1-1972",
  },
  {
    audNum: 96,
    title: "Ephesians Parallels Joshua #2",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "October-8-1972",
  },
  {
    audNum: 97,
    title: "Ephesians Parallels Joshua #3",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "October-8-1972",
  },
  {
    audNum: 98,
    title: "Ephesians Parallels Joshua #4",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "October-15-1972",
  },
  {
    audNum: 99,
    title: "Ephesians Parallels Joshua #5",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "October-15-1972",
  },
  {
    audNum: 100,
    title: "Ephesians Parallels Joshua #6",
    type: "mp3",
    audioUrl:'',
    year: "1973",
    date: "February-11-1973",
  },
  {
    audNum: 101,
    title: "Evening Light",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "November-29-1970",
  },
  {
    audNum: 102,
    title: "Ever Learning - Never Able",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "March-10-1971",
  },
  {
    audNum: 103,
    title: "Evil Communication (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "June-5-1969",
  },
  {
    audNum: 104,
    title: "Evil Communication (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "June-5-1969",
  },
  {
    audNum: 105,
    title: "Evil Heart Of Unbelief",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "April-12-1970",
  },
  {
    audNum: 106,
    title: "Eye To The Body (Diego Martin, Trinidad) (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "December-21-1972",
  },
  {
    audNum: 107,
    title: "Eye To The Body (Diego Martin, Trinidad) (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "December-21-1972",
  },
  {
    audNum: 108,
    title: "Ezekiel 47",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "July-12-1970",
  },
  {
    audNum: 109,
    title: "Faith For The Supernatural Birth (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "October-31-1971",
  },
  {
    audNum: 110,
    title: "Faith For The Supernatural Birth (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "October-31-1971",
  },
  {
    audNum: 111,
    title: "Falling Away From The Faith",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "May-19-1968",
  },
  {
    audNum: 112,
    title: "False Christs",
    type: "mp3",
    audioUrl:'',
    year: "1973",
    date: "April-8-1973",
  },
  {
    audNum: 113,
    title: "Fasting For Revival",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "September-24-1972",
  },
  {
    audNum: 114,
    title: "Fellowship (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "January-3-1971",
  },
  {
    audNum: 115,
    title: "Fellowship (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "January-3-1971",
  },
  {
    audNum: 116,
    title: "Following Apostolic Pattern",
    type: "mp3",
    audioUrl:'',
    year: "1967",
    date: "June-25-1967",
  },
  {
    audNum: 117,
    title:
      "Following The Son Of Man In Regeneration In The Evening Time (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "July-12-1970",
  },
  {
    audNum: 118,
    title:
      "Following The Son Of Man In Regeneration In The Evening Time (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "July-12-1970",
  },
  {
    audNum: 119,
    title: "Foundation Was Laid",
    type: "mp3",
    audioUrl:'',
    year: "1967",
    date: "December-10-1967",
  },
  {
    audNum: 120,
    title: "From Darkness To Light #1",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "December-20-1970",
  },
  {
    audNum: 121,
    title: "From Darkness To Light #2 (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "December-20-1970",
  },
  {
    audNum: 122,
    title: "From Darkness To Light #2 (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "December-20-1970",
  },
  {
    audNum: 123,
    title: "Fullness Of Time",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "August-13-1970",
  },
  {
    audNum: 124,
    title: "Gathering Together Of Elected (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "November-16-1969",
  },
  {
    audNum: 125,
    title: "Gathering Together Of Elected (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "November-16-1969",
  },
  {
    audNum: 126,
    title: "GOD Creating A Thirst In The Bride",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "July-11-1971",
  },
  {
    audNum: 127,
    title: "GOD Creating A Thirst In The Elected Bride (Jeff, In)",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "August-25-1972",
  },
  {
    audNum: 128,
    title: "God Honors His Word Above His Name",
    type: "mp3",
    audioUrl:'',
    year: "1961",
    date: "December-31-1961",
  },
  {
    audNum: 129,
    title: "GOD Measuring Out The Spirit",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "May-14-1972",
  },
  {
    audNum: 130,
    title: "GOD's Faithful Servant (#1)",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "April-9-1972",
  },
  {
    audNum: 131,
    title: "GOD's Faithful Servant (#2)",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "April-16-1972",
  },
  {
    audNum: 132,
    title: "GOD'S Unconditional Covenant To The Elected Bride (#1)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "November-28-1971",
  },
  {
    audNum: 133,
    title: "GOD'S Unconditional Covenant To The Elected Bride (#2) (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "December-5-1971",
  },
  {
    audNum: 134,
    title: "GOD'S Unconditional Covenant To The Elected Bride (#2) (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "December-5-1971",
  },
  {
    audNum: 135,
    title: "GOD'S Unconditional Covenant To The Elected Bride (#3)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "December-5-1971",
  },
  {
    audNum: 136,
    title: "God's Day Of Wrath (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "June-23-1968",
  },
  {
    audNum: 137,
    title: "God's Day Of Wrath (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "June-23-1968",
  },
  {
    audNum: 138,
    title: "God's End Time Sign",
    type: "mp3",
    audioUrl:'',
    year: "1967",
    date: "July-16-1967",
  },
  {
    audNum: 139,
    title: "God's Gift",
    type: "mp3",
    audioUrl:'',
    year: "1967",
    date: "December-17-1967",
  },
  {
    audNum: 140,
    title: "God's Only Way Of Escape In A Day Of Wrath And Judgment (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "November-23-1969",
  },
  {
    audNum: 141,
    title: "God's Only Way Of Escape In A Day Of Wrath And Judgment (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "November-23-1969",
  },
  {
    audNum: 142,
    title: "God's Perfect Love",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "February-7-1971",
  },
  {
    audNum: 143,
    title: "God's Provided Way To Bring Unity (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "October-12-1969",
  },
  {
    audNum: 144,
    title: "God's Provided Way To Bring Unity (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "October-12-1969",
  },
  {
    audNum: 145,
    title: "God's Sovereign In His Actions",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "July-27-1969",
  },
  {
    audNum: 146,
    title: "Golden Nuggets",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "August-15-1968",
  },
  {
    audNum: 147,
    title: "Goodman Of The House",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "April-6-1969",
  },
  {
    audNum: 148,
    title: "Harvest Time (#1)",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "July-29-1972",
  },
  {
    audNum: 149,
    title: "Harvest Time (#2)",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "July-30-1972",
  },
  {
    audNum: 150,
    title: "Harvest Time (#3)",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "July-30-1972",
  },
  {
    audNum: 151,
    title: "Hated Because Of Coat Of Many Colors",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "August-30-1970",
  },
  {
    audNum: 152,
    title: "He Must Need Go Through Samaria (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "October-12-1969",
  },
  {
    audNum: 153,
    title: "He Must Need Go Through Samaria (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "October-12-1969",
  },
  {
    audNum: 154,
    title: "Hearers Of The Prophet Of Mal 4:5",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "January-4-1970",
  },
  {
    audNum: 155,
    title: "Hedged In With God",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "February-1-1970",
  },
  {
    audNum: 156,
    title: "Hour Of Satan's Working",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "September-21-1969",
  },
  {
    audNum: 157,
    title: "Hour Of Temptation (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "June-14-1970",
  },
  {
    audNum: 158,
    title: "Hour Of Temptation (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "June-14-1970",
  },
  {
    audNum: 159,
    title: "How To Be Born Again And How To Enter In (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "March-9-1969",
  },
  {
    audNum: 160,
    title: "How To Be Born Again And How To Enter In (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "March-9-1969",
  },
  {
    audNum: 161,
    title: "How To Enter In God's Ark Today (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "March-20-1969",
  },
  {
    audNum: 162,
    title: "How To Enter In God's Ark Today (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "March-20-1969",
  },
  {
    audNum: 163,
    title: "How To Receive The Baptism Of The Holy Ghost",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "March-13-1969",
  },
  {
    audNum: 164,
    title: "Illegitimate Born Children (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "June-8-1969",
  },
  {
    audNum: 165,
    title: "Illegitimate Born Children (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "June-8-1969",
  },
  {
    audNum: 166,
    title: "Influence",
    type: "mp3",
    audioUrl:'',
    year: "1973",
    date: "March-14-1973",
  },
  {
    audNum: 167,
    title: "Inheritance In Christ (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "August-9-1970",
  },
  {
    audNum: 168,
    title: "Inheritance In Christ (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "August-9-1970",
  },
  {
    audNum: 169,
    title: "Initial Evidence Of The Holy Ghost",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "February-2-1972",
  },
  {
    audNum: 170,
    title: "Introducing The Messiah",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "July-17-1969",
  },
  {
    audNum: 171,
    title: "Introduction Of Messiah (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "August-2-1970",
  },
  {
    audNum: 172,
    title: "Introduction Of Messiah (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "August-2-1970",
  },
  {
    audNum: 173,
    title: "Inviting Jesus Into The Ship",
    type: "mp3",
    audioUrl:'',
    year: "1973",
    date: "February-7-1973",
  },
  {
    audNum: 174,
    title: "Israel Trip",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "September-25-1969",
  },
  {
    audNum: 175,
    title: "Jesus And Peter",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "March-16-1969",
  },
  {
    audNum: 176,
    title: "Joseph",
    type: "mp3",
    audioUrl:'',
    year: "1973",
    date: "January-28-1973",
  },
  {
    audNum: 177,
    title: "Joy",
    type: "mp3",
    audioUrl:'',
    year: "1964",
    date: "April-17-1964",
  },
  {
    audNum: 178,
    title: "Joy Unspeakable",
    type: "mp3",
    audioUrl:'',
    year: "1964",
    date: "April-15-1964",
  },
  {
    audNum: 179,
    title: "Knowing Your Enemy",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "May-19-1971",
  },
  {
    audNum: 180,
    title: "Last Separation Before Promise Blessing",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "April-24-1969",
  },
  {
    audNum: 181,
    title: "Led By The Spirit",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "May-16-1971",
  },
  {
    audNum: 182,
    title: "Lesson On Perfect Faith (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "October-24-1971",
  },
  {
    audNum: 183,
    title: "Lesson On Perfect Faith (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "October-24-1971",
  },
  {
    audNum: 184,
    title: "Liberty",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "September-20-1972",
  },
  {
    audNum: 185,
    title: "Light",
    type: "mp3",
    audioUrl:'',
    year: "1973",
    date: "July-8-1973",
  },
  {
    audNum: 186,
    title: "Living Bread & Body Of The Lord Jesus",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "August-4-1968",
  },
  {
    audNum: 187,
    title: "Living Temple",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "February-11-1968",
  },
  {
    audNum: 188,
    title: "Looking For Christ To Come (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "November-8-1970",
  },
  {
    audNum: 189,
    title: "Looking For Christ To Come (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "November-8-1970",
  },
  {
    audNum: 190,
    title: "Mal. 3:1-3, 4:5 The Waymaker (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "June-28-1970",
  },
  {
    audNum: 191,
    title: "Mal. 3:1-3, 4:5 The Waymaker (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "June-28-1970",
  },
  {
    audNum: 192,
    title: "Messages Come To Shepherds-Feed My Sheep",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "May-12-1968",
  },
  {
    audNum: 193,
    title: "Messenger Of The Covenant",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "September-29-1968",
  },
  {
    audNum: 194,
    title: "Ministry Of The Bride #1 (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "January-2-1972",
  },
  {
    audNum: 195,
    title: "Ministry Of The Bride #1 (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "January-2-1972",
  },
  {
    audNum: 196,
    title: "Ministry Of The Bride #2",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "January-2-1972",
  },
  {
    audNum: 197,
    title: "Moses` Sin & Smitten Rock (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "February-2-1969",
  },
  {
    audNum: 198,
    title: "Moses` Sin & Smitten Rock (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "February-2-1969",
  },
  {
    audNum: 199,
    title: "Mystery Of God's Will",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "May-31-1970",
  },
  {
    audNum: 200,
    title: "New Year's Eve Service (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "December-31-1970",
  },
  {
    audNum: 201,
    title: "New Year's Eve Service (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "December-31-1970",
  },
  {
    audNum: 202,
    title: "No Condemnation To Those In Christ",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "May-2-1971",
  },
  {
    audNum: 203,
    title: "Nuggets (Bob & Shirleys Dreams Of Mark)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "September-22-1971",
  },
  {
    audNum: 204,
    title: "Obtaining Mercy And Grace",
    type: "mp3",
    audioUrl:'',
    year: "1973",
    date: "February-14-1973",
  },
  {
    audNum: 205,
    title: "Oneness",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "April-21-1968",
  },
  {
    audNum: 206,
    title: "Our Foundation Today (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "January-31-1971",
  },
  {
    audNum: 207,
    title: "Our Foundation Today (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "January-31-1971",
  },
  {
    audNum: 208,
    title: "Our Redeemer #1",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "October-13-1968",
  },
  {
    audNum: 209,
    title: "Our Redeemer #2",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "October-20-1968",
  },
  {
    audNum: 210,
    title: "Our Redeemer #3 (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "November-3-1968",
  },
  {
    audNum: 211,
    title: "Our Redeemer #3 (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "November-3-1968",
  },
  {
    audNum: 212,
    title: "Our Redeemer #4",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "November-10-1968",
  },
  {
    audNum: 213,
    title: "Parable Of The Net",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "January-3-1971",
  },
  {
    audNum: 214,
    title: "Parable Of The Vineyard (#1)",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "July-16-1972",
  },
  {
    audNum: 215,
    title: "Parable Of The Vineyard (#2)",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "July-16-1972",
  },
  {
    audNum: 216,
    title: "Parable On Eleventh Hour Gentile Worker (Jeff, In) (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "August-20-1972",
  },
  {
    audNum: 217,
    title: "Parable On Eleventh Hour Gentile Worker (Jeff, In) (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "August-20-1972",
  },
  {
    audNum: 218,
    title: "Patience (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1967",
    date: "November-5-1967",
  },
  {
    audNum: 219,
    title: "Patience (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1967",
    date: "November-5-1967",
  },
  {
    audNum: 220,
    title: "Patience To Inherit The Promise",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "July-24-1969",
  },
  {
    audNum: 221,
    title: "Patience To Wait On God's Promise (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "March-8-1970",
  },
  {
    audNum: 222,
    title: "Patience To Wait On God's Promise (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "March-8-1970",
  },
  {
    audNum: 223,
    title: "Payday-Payoff (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "July-25-1971",
  },
  {
    audNum: 224,
    title: "Payday-Payoff (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "July-25-1971",
  },
  {
    audNum: 225,
    title: "Perfection",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "August-18-1968",
  },
  {
    audNum: 226,
    title: "Perfection (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "October-25-1970",
  },
  {
    audNum: 227,
    title: "Perfection (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "October-25-1970",
  },
  {
    audNum: 228,
    title: "Persuasion By Influence",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "May-10-1970",
  },
  {
    audNum: 229,
    title: "Planted By God #1 (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "September-27-1970",
  },
  {
    audNum: 230,
    title: "Planted By God #1 (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "September-27-1970",
  },
  {
    audNum: 231,
    title: "Planted By God #2",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "September-27-1970",
  },
  {
    audNum: 232,
    title: "Planted By God #3",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "October-1-1970",
  },
  {
    audNum: 233,
    title: "Positionally Placed Last Time Bride (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "May-10-1970",
  },
  {
    audNum: 234,
    title: "Positionally Placed Last Time Bride (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "May-10-1970",
  },
  {
    audNum: 235,
    title: "Potential",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "August-27-1970",
  },
  {
    audNum: 236,
    title: "Power For Service",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "December-6-1970",
  },
  {
    audNum: 237,
    title: "Power To Loose And Bind",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "July-20-1969",
  },
  {
    audNum: 238,
    title: "Prayer",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "November-5-1969",
  },
  {
    audNum: 239,
    title: "Preparation For Fulfillment Of The Reveled Promise",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "April- 25-1971",
  },
  {
    audNum: 240,
    title: "Proper Doctrine",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "April- 19-1972",
  },
  {
    audNum: 241,
    title: "Psalms 91 & 95",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "June- 25-1970",
  },
  {
    audNum: 242,
    title: "Questions & Answers #1 (Tree Of Life)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "February- 9-1971",
  },
  {
    audNum: 243,
    title: "Questions & Answers #10",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "April- 12-1972",
  },
  {
    audNum: 244,
    title: "Questions & Answers #2",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "June- 2-1971",
  },
  {
    audNum: 245,
    title: "Questions & Answers #3",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "June- 16-1971",
  },
  {
    audNum: 246,
    title: "Questions & Answers #4",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "June- 23-1971",
  },
  {
    audNum: 247,
    title: "Questions & Answers #5",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "July- 28-1971",
  },
  {
    audNum: 248,
    title: "Questions & Answers #6 (Bride-Serpent Seed)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "August- 14-1971",
  },
  {
    audNum: 249,
    title: "Questions & Answers #7 ( New Birth )",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "October- 27-1971",
  },
  {
    audNum: 250,
    title: "Questions & Answers #8",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "May- 3-1972",
  },
  {
    audNum: 251,
    title: "Questions & Answers #9",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "March- 15-1972",
  },
  {
    audNum: 252,
    title: "Rahab And The Scarlet Cord (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "August- 29-1971",
  },
  {
    audNum: 253,
    title: "Rahab And The Scarlet Cord (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "August- 29-1971",
  },
  {
    audNum: 254,
    title: "Rapturing Faith (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "July- 20-1969",
  },
  {
    audNum: 255,
    title: "Rapturing Faith (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "July- 20-1969",
  },
  {
    audNum: 256,
    title: "Recongnizing The Promise And Making Preparation For Fulfillment",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "June- 27-1971",
  },
  {
    audNum: 257,
    title: "Redemption By The Blood (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "January- 25-1970",
  },
  {
    audNum: 258,
    title: "Redemption By The Blood (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "January- 25-1970",
  },
  {
    audNum: 259,
    title: "Rejecting God's Council (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "April- 20-1969",
  },
  {
    audNum: 260,
    title: "Rejecting God's Council (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "April- 20-1969",
  },
  {
    audNum: 261,
    title: "Remarks To The Church",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "September- 5-1971",
  },
  {
    audNum: 262,
    title: "Remember Lot's Wife (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "June- 4-1972",
  },
  {
    audNum: 263,
    title: "Remember Lot's Wife (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "June- 4-1972",
  },
  {
    audNum: 264,
    title: "Reproach For The Word",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "July- 27-1969",
  },
  {
    audNum: 265,
    title: "Respect To God's Anointed Servants (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "August- 20-1970",
  },
  {
    audNum: 266,
    title: "Respect To God's Anointed Servants (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "August- 20-1970",
  },
  {
    audNum: 267,
    title: "Restoration",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "February- 11-1968",
  },
  {
    audNum: 268,
    title: "Restoration",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "May- 3-1970",
  },
  {
    audNum: 269,
    title: "Rev. Of His Will For Us (#1)",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "December- 26-1972",
  },
  {
    audNum: 270,
    title: "Rev. Of His Will For Us (#2)",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "December- 26-1972",
  },
  {
    audNum: 271,
    title: "Rev. Of The Son Of Man",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "January- 28-1968",
  },
  {
    audNum: 272,
    title: "Rich & Have Need Of Nothing",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "January- 21-1968",
  },
  {
    audNum: 273,
    title: "Righteousness & Justification #1",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "July- 9-1970",
  },
  {
    audNum: 274,
    title: "Righteousness & Justification #2",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "July- 23-1970",
  },
  {
    audNum: 275,
    title: "Rivers Of Unbelief & Bride Out Of Step (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "January- 14-1968",
  },
  {
    audNum: 276,
    title: "Rivers Of Unbelief & Bride Out Of Step (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "January- 14-1968",
  },
  {
    audNum: 277,
    title: "Salt Without Savour",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "August- 11-1968",
  },
  {
    audNum: 278,
    title: "Satan And Job (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "September- 21-1969",
  },
  {
    audNum: 279,
    title: "Satan And Job (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "September- 21-1969",
  },
  {
    audNum: 280,
    title: "Scoffers Of The Promise",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "January- 7-1971",
  },
  {
    audNum: 281,
    title: "Second Hand Religion",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "May- 14-1972",
  },
  {
    audNum: 282,
    title: "Seeking Love",
    type: "mp3",
    audioUrl:'',
    year: "1973",
    date: "April- 8-1973",
  },
  {
    audNum: 283,
    title: "Seeking The Lord For Revival",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "September- 9-1972",
  },
  {
    audNum: 284,
    title: "Seeking To Find Jesus (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "April- 6-1969",
  },
  {
    audNum: 285,
    title: "Seeking To Find Jesus (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "April- 6-1969",
  },
  {
    audNum: 286,
    title: "Shamgar",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "October- 20-1968",
  },
  {
    audNum: 287,
    title: "Sleepless Prayer",
    type: "mp3",
    audioUrl:'',
    year: "1964",
    date: "October- 14-1964",
  },
  {
    audNum: 288,
    title: "Some Standing Here",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "December- 3-1970",
  },
  {
    audNum: 289,
    title: "Something You Can Do",
    type: "mp3",
    audioUrl:'',
    year: "1973",
    date: "April- 25-1973",
  },
  {
    audNum: 290,
    title: "Son Of Man (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "June- 21-1970",
  },
  {
    audNum: 291,
    title: "Son Of Man (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "June- 21-1970",
  },
  {
    audNum: 292,
    title: "Son Of Man And His Angels #1 (Jeff, In) (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1973",
    date: "January- 20-1973",
  },
  {
    audNum: 293,
    title: "Son Of Man And His Angels #1 (Jeff, In) (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1973",
    date: "January- 20-1973",
  },
  {
    audNum: 294,
    title: "Son Of Man And His Angels #2 (Jeff, In)",
    type: "mp3",
    audioUrl:'',
    year: "1973",
    date: "January- 21-1973",
  },
  {
    audNum: 295,
    title: "Son Of Man And The Little Book (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "March- 21-1971",
  },
  {
    audNum: 296,
    title: "Son Of Man And The Little Book (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "March- 21-1971",
  },
  {
    audNum: 297,
    title: "Son Of Man Ministry",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "June- 28-1972",
  },
  {
    audNum: 298,
    title: "Son's Back To Eden",
    type: "mp3",
    audioUrl:'',
    year: "1967",
    date: "August- 10-1967",
  },
  {
    audNum: 299,
    title: "Sound Doctrine (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "June- 2-1968",
  },
  {
    audNum: 300,
    title: "Sound Doctrine (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "June- 2-1968",
  },
  {
    audNum: 301,
    title: "Spirit Of Christ",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "June- 30-1968",
  },
  {
    audNum: 302,
    title: "Spirit Of Elijah (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "June- 16-1968",
  },
  {
    audNum: 303,
    title: "Spirit Of Elijah (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "June- 16-1968",
  },
  {
    audNum: 304,
    title: "Spirit Of Moses (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "June- 23-1968",
  },
  {
    audNum: 305,
    title: "Spirit Of Moses (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "June- 23-1968",
  },
  {
    audNum: 306,
    title: "Spirit Of The Son Of Man",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "July- 7-1968",
  },
  {
    audNum: 307,
    title: "Spiritual Cancer",
    type: "mp3",
    audioUrl:'',
    year: "1967",
    date: "August- 3-1967",
  },
  {
    audNum: 308,
    title: "Spoken Word Original Seed #1 (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "May- 23-1971",
  },
  {
    audNum: 309,
    title: "Spoken Word Original Seed #1 (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "May- 23-1971",
  },
  {
    audNum: 310,
    title: "Spoken Word Original Seed #2",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "May- 23-1971",
  },
  {
    audNum: 311,
    title: "Spoken Word Original Seed #3 (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "July- 18-1971",
  },
  {
    audNum: 312,
    title: "Spoken Word Original Seed #3 (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "July- 18-1971",
  },
  {
    audNum: 313,
    title: "Spoken Word Original Seed #4 (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "August- 8-1971",
  },
  {
    audNum: 314,
    title: "Spoken Word Original Seed #4 (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "August- 8-1971",
  },
  {
    audNum: 315,
    title: "Study-Christ The Mystery Of God Revealed (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "November- 24-1968",
  },
  {
    audNum: 316,
    title: "Study-Christ The Mystery Of God Revealed (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "November- 24-1968",
  },
  {
    audNum: 317,
    title: "Substitute (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "June- 15-1969",
  },
  {
    audNum: 318,
    title: "Substitute (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "June- 15-1969",
  },
  {
    audNum: 319,
    title: "Sun Of Righteousness",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "July- 9-1972",
  },
  {
    audNum: 320,
    title: "Take Heed How You Hear (Durham, CT)",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "March- 19-1972",
  },
  {
    audNum: 321,
    title: "Take Heed How You Hear (Jeff, In)",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "August- 26-1972",
  },
  {
    audNum: 322,
    title: "Tape-One More Time WMB, R. Lambert (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "January- 17-1971",
  },
  {
    audNum: 323,
    title: "Tape-One More Time WMB, R. Lambert (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "January- 17-1971",
  },
  {
    audNum: 324,
    title: "Tape-Testing Time-WMB",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "January- 31-1971",
  },
  {
    audNum: 325,
    title: "Tender Mercies Of GOD",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "April- 16-1972",
  },
  {
    audNum: 326,
    title: "Testing Before Blessing",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "February- 4-1968",
  },
  {
    audNum: 327,
    title: "Testing For Discipleship By The Revealed Word",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "August- 11-1971",
  },
  {
    audNum: 328,
    title: "The Blood Speaks (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "January- 30-1972",
  },
  {
    audNum: 329,
    title: "The Blood Speaks (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "January- 30-1972",
  },
  {
    audNum: 330,
    title: "The Capstone",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "September- 16-1972",
  },
  {
    audNum: 331,
    title: "The Cares Of This Life",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "November- 10-1968",
  },
  {
    audNum: 332,
    title: "The Coming Of The King",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "December- 6-1972",
  },
  {
    audNum: 333,
    title: "The Cup Of Salvation #1 (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "November- 15-1970",
  },
  {
    audNum: 334,
    title: "The Cup Of Salvation #1 (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "November- 15-1970",
  },
  {
    audNum: 335,
    title: "The Cup Of Salvation #2",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "November- 15-1970",
  },
  {
    audNum: 336,
    title: "The Days Of Noe (Last Message Preached)",
    type: "mp3",
    audioUrl:'',
    year: "1973",
    date: "August- 1-1973",
  },
  {
    audNum: 337,
    title: "The Divine Sculptor's Masterpiece",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "May- 26-1968",
  },
  {
    audNum: 338,
    title: "The Eunuchs Of The Lord Jesus Christ",
    type: "mp3",
    audioUrl:'',
    year: "1966",
    date: "April- 1-1966",
  },
  {
    audNum: 339,
    title: "The Evil Nature",
    type: "mp3",
    audioUrl:'',
    year: "1964",
    date: "October- 11-1964",
  },
  {
    audNum: 340,
    title: "The Eye To The Body (Jeff, In)",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "August- 20-1972",
  },
  {
    audNum: 341,
    title: "The Eyes Of The Lord (In Relation To The Body Of Christ)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "October- 3-1971",
  },
  {
    audNum: 342,
    title: "The Friend Of The Bridegroom",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "April- 12-1970",
  },
  {
    audNum: 343,
    title: "The Godhead",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "October- 30-1969",
  },
  {
    audNum: 344,
    title: "The Good Samaritan",
    type: "mp3",
    audioUrl:'',
    year: "1967",
    date: "July- 30-1967",
  },
  {
    audNum: 345,
    title: "The Great Physician (In Relation To Pregnancy & Birth) (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "January- 24-1971",
  },
  {
    audNum: 346,
    title: "The Great Physician (In Relation To Pregnancy & Birth) (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "January- 24-1971",
  },
  {
    audNum: 347,
    title: "The Great Whore (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "October- 19-1969",
  },
  {
    audNum: 348,
    title: "The Great Whore (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "October- 19-1969",
  },
  {
    audNum: 349,
    title: "The Great Word Test",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "June- 4-1972",
  },
  {
    audNum: 350,
    title: "The Great Word Test (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "March- 7-1971",
  },
  {
    audNum: 351,
    title: "The Great Word Test (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "March- 7-1971",
  },
  {
    audNum: 352,
    title: "The Hardening Heart",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "February- 18-1968",
  },
  {
    audNum: 353,
    title: "The Hireling Shepherd",
    type: "mp3",
    audioUrl:'',
    year: "1965",
    date: "April- 11-1965",
  },
  {
    audNum: 354,
    title: "The Image Of The Invisible GOD",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "November- 21-1971",
  },
  {
    audNum: 355,
    title: "The Invisible GOD Made Visible",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "October- 31-1971",
  },
  {
    audNum: 356,
    title: "The Kingdom Is Rent From Thee (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "November- 17-1968",
  },
  {
    audNum: 357,
    title: "The Kingdom Is Rent From Thee (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "November- 17-1968",
  },
  {
    audNum: 358,
    title: "The Last Day Ministry",
    type: "mp3",
    audioUrl:'',
    year: "1965",
    date: "October- 15-1965",
  },
  {
    audNum: 359,
    title: "The Latter Rain",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "July- 11-1971",
  },
  {
    audNum: 360,
    title: "The Lightning Of The Candle",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "June- 27-1971",
  },
  {
    audNum: 361,
    title: "The Lost Capstone",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "September- 17-1972",
  },
  {
    audNum: 362,
    title: "The Man Child",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "October- 22-1972",
  },
  {
    audNum: 363,
    title: "The Man-Child Made Manifested In This Hour",
    type: "mp3",
    audioUrl:'',
    year: "1966",
    date: "August- 13-1966",
  },
  {
    audNum: 364,
    title: "The Mind Of Christ",
    type: "mp3",
    audioUrl:'',
    year: "1967",
    date: "January- 1-1967",
  },
  {
    audNum: 365,
    title: "The Ministry Of The Bride",
    type: "mp3",
    audioUrl:'',
    year: "1967",
    date: "April- 23-1967",
  },
  {
    audNum: 366,
    title: "The Perfect Word For The Perfect Day (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "February- 7-1971",
  },
  {
    audNum: 367,
    title: "The Perfect Word For The Perfect Day (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "February- 7-1971",
  },
  {
    audNum: 368,
    title: "The Return Of The Same Jesus (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "August- 22-1971",
  },
  {
    audNum: 369,
    title: "The Return Of The Same Jesus (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "August- 22-1971",
  },
  {
    audNum: 370,
    title: "The Things Concerning Himself",
    type: "mp3",
    audioUrl:'',
    year: "1973",
    date: "May- 30-1973",
  },
  {
    audNum: 371,
    title: "The Token (#1) (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "March- 22-1970",
  },
  {
    audNum: 372,
    title: "The Token (#1) (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "March- 22-1970",
  },
  {
    audNum: 373,
    title: "The Token (#2) (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "March- 22-1970",
  },
  {
    audNum: 374,
    title: "The Token (#2) (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "March- 22-1970",
  },
  {
    audNum: 375,
    title: "The Token Nuggets (#1)",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "July- 23-1972",
  },
  {
    audNum: 376,
    title: "The Token Nuggets (#2)",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "July- 23-1972",
  },
  {
    audNum: 377,
    title: "The Truth Shall Make You Free (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "February- 28-1971",
  },
  {
    audNum: 378,
    title: "The Truth Shall Make You Free (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "February- 28-1971",
  },
  {
    audNum: 379,
    title: "The Vision Today",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "August- 22-1971",
  },
  {
    audNum: 380,
    title: "The Voice Of The Archangel",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "November- 22-1970",
  },
  {
    audNum: 381,
    title: "The Voice Of The Archangel #1 (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1973",
    date: "January- 14-1973",
  },
  {
    audNum: 382,
    title: "The Voice Of The Archangel #1 (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1973",
    date: "January- 14-1973",
  },
  {
    audNum: 383,
    title: "The Voice Of The Archangel #2",
    type: "mp3",
    audioUrl:'',
    year: "1973",
    date: "January- 14-1973",
  },
  {
    audNum: 384,
    title: "The Voice That Catches The Bride (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "November- 22-1970",
  },
  {
    audNum: 385,
    title: "The Voice That Catches The Bride (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "November- 22-1970",
  },
  {
    audNum: 386,
    title: "The Way Of Salvation",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "November- 8-1970",
  },
  {
    audNum: 387,
    title: "The Word Of His Patience",
    type: "mp3",
    audioUrl:'',
    year: "1973",
    date: "May- 23-1973",
  },
  {
    audNum: 388,
    title: "Things Reproved Are Made Manifested",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "October- 4-1970",
  },
  {
    audNum: 389,
    title: "Tormenting The Ungodly (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "November- 17-1968",
  },
  {
    audNum: 390,
    title: "Tormenting The Ungodly (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "November- 17-1968",
  },
  {
    audNum: 391,
    title: "Trinidad Service",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "December- 23-1972",
  },
  {
    audNum: 392,
    title: 'Trinidad Service "Son Of Man" (Part 1)',
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "December- 24-1972",
  },
  {
    audNum: 393,
    title: 'Trinidad Service "Son Of Man" (Part 2)',
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "December- 24-1972",
  },
  {
    audNum: 394,
    title: "Trinidad Trip & Ministers Testimonies",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "January- 19-1972",
  },
  {
    audNum: 395,
    title: "Troubling Of Waters",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "November- 1-1970",
  },
  {
    audNum: 396,
    title: "True Atonement (Christ Rev. From Heaven) (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "May- 7-1972",
  },
  {
    audNum: 397,
    title: "True Atonement (Christ Rev. From Heaven) (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "May- 7-1972",
  },
  {
    audNum: 398,
    title: "True Church",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "April- 23-1970",
  },
  {
    audNum: 399,
    title: "Trumpet Of Jubilee (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "March- 16-1969",
  },
  {
    audNum: 400,
    title: "Trumpet Of Jubilee (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "March- 16-1969",
  },
  {
    audNum: 401,
    title: "Truth",
    type: "mp3",
    audioUrl:'',
    year: "1973",
    date: "May- 6-1973",
  },
  {
    audNum: 402,
    title: "Two Great Women And Their Reward",
    type: "mp3",
    audioUrl:'',
    year: "1967",
    date: "December- 10-1967",
  },
  {
    audNum: 403,
    title: "Two Kingdoms #1 (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "September- 13-1970",
  },
  {
    audNum: 404,
    title: "Two Kingdoms #1 (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "September- 13-1970",
  },
  {
    audNum: 405,
    title: "Two Kingdoms #2 (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "September- 13-1970",
  },
  {
    audNum: 406,
    title: "Two Kingdoms #2 (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "September- 13-1970",
  },
  {
    audNum: 407,
    title: "Two Kingdoms #3 (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "September- 14-1970",
  },
  {
    audNum: 408,
    title: "Two Kingdoms #3 (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "September- 14-1970",
  },
  {
    audNum: 409,
    title: "Two Kingdoms #4 (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "April- 11-1971",
  },
  {
    audNum: 410,
    title: "Two Kingdoms #4 (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "April- 11-1971",
  },
  {
    audNum: 411,
    title: "Two Kingdoms #5 (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "April- 18-1970",
  },
  {
    audNum: 412,
    title: "Two Kingdoms #5 (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "April- 18-1970",
  },
  {
    audNum: 413,
    title: "Two Kingdoms #6 (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "April- 18-1971",
  },
  {
    audNum: 414,
    title: "Two Kingdoms #6 (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "April- 18-1971",
  },
  {
    audNum: 415,
    title: "Two Trees In Eden (#1)",
    type: "mp3",
    audioUrl:'',
    year: "1973",
    date: "March- 18-1973",
  },
  {
    audNum: 416,
    title: "Two Trees In Eden (#2)",
    type: "mp3",
    audioUrl:'',
    year: "1973",
    date: "March- 18-1973",
  },
  {
    audNum: 417,
    title: "Unclean Spirits Like Frogs (#1)",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "August- 6-1972",
  },
  {
    audNum: 418,
    title: "Unclean Spirits Like Frogs (#2)",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "August- 6-1972",
  },
  {
    audNum: 419,
    title: "Vain Jangling",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "July- 25-1969",
  },
  {
    audNum: 420,
    title: "Villa Capri",
    type: "mp3",
    audioUrl:'',
    year: "1961",
    date: "July- 22-1961",
  },
  {
    audNum: 421,
    title: "Walking In The Light With Eye Single",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "September- 19-1971",
  },
  {
    audNum: 422,
    title: "Walking On The Water",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "November- 9-1969",
  },
  {
    audNum: 423,
    title: "Wandering Thoughts",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "February- 6-1969",
  },
  {
    audNum: 424,
    title: "Wedding Garment",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "February- 15-1970",
  },
  {
    audNum: 425,
    title: "What Price Token #1 (Pearl Of Great Price)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "August- 23-1970",
  },
  {
    audNum: 426,
    title: "What Price Token #2 (Parable Of The Net)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "August- 23-1970",
  },
  {
    audNum: 427,
    title: "What's Upon My Heart #1 (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "April- 27-1969",
  },
  {
    audNum: 428,
    title: "What's Upon My Heart #1 (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "April- 27-1969",
  },
  {
    audNum: 429,
    title: "What's Upon My Heart #2 (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "April- 27-1969",
  },
  {
    audNum: 430,
    title: "What's Upon My Heart #2 (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "April- 27-1969",
  },
  {
    audNum: 431,
    title: "Who Can Be Saved",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "February- 28-1971",
  },
  {
    audNum: 432,
    title: "Who Gets The Token In The Endtime",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "January- 14-1971",
  },
  {
    audNum: 433,
    title: "Who Hath Believed Our Report (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "September- 29-1968",
  },
  {
    audNum: 434,
    title: "Who Hath Believed Our Report (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "September- 29-1968",
  },
  {
    audNum: 435,
    title: "Who Hath Belived Our Report (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "March- 14-1971",
  },
  {
    audNum: 436,
    title: "Who Hath Belived Our Report (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "March- 14-1971",
  },
  {
    audNum: 437,
    title: "Who Understandeth God",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "October- 8-1970",
  },
  {
    audNum: 438,
    title: "Why Did God Hate Esau (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "October- 26-1969",
  },
  {
    audNum: 439,
    title: "Why Did God Hate Esau (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "October- 26-1969",
  },
  {
    audNum: 440,
    title: "Why God Hated Esau",
    type: "mp3",
    audioUrl:'',
    year: "1973",
    date: "January- 28-1973",
  },
  {
    audNum: 441,
    title: "Why Is Christ Rejected Today",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "September- 3-1970",
  },
  {
    audNum: 442,
    title: "Why Judas Was Not Saved",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "December- 22-1971",
  },
  {
    audNum: 443,
    title: "Why Our Prayers Not Answered",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "November- 21-1971",
  },
  {
    audNum: 444,
    title: "Woman At The Well (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "May- 3-1971",
  },
  {
    audNum: 445,
    title: "Woman At The Well (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "May- 3-1971",
  },
  {
    audNum: 446,
    title: "Woman At The Well (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "May- 3-1970",
  },
  {
    audNum: 447,
    title: "Woman At The Well (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "May- 3-1970",
  },
  {
    audNum: 448,
    title: "Women At The Well",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "May- 28-1972",
  },
  {
    audNum: 449,
    title: "Word Atonement For The Bride (#1)",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "January- 23-1972",
  },
  {
    audNum: 450,
    title: "Word Atonement For The Bride (#2)",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "January- 23-1972",
  },
  {
    audNum: 451,
    title: "Word Atonement For The Bride (#3)",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "January- 26-1972",
  },
  {
    audNum: 452,
    title: "Word Of Promise (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "February- 8-1970",
  },
  {
    audNum: 453,
    title: "Word Of Promise (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1970",
    date: "February- 8-1970",
  },
  {
    audNum: 454,
    title: "Your Adversary",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "January- 28-1971",
  },
  {
    audNum: 455,
    title: "Your Revelation Is The Victory (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "October- 26-1969",
  },
  {
    audNum: 456,
    title: "Your Revelation Is The Victory (Part 2)",
    type: "mp3",
    audioUrl:'',
    year: "1969",
    date: "October- 26-1969",
  },
];

export default audioSermons;