const audioSermons = [
  {
    audNum:'1m',
    title: "Be Unified",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/be-unified/',
    year: "1970",
    date: "November-5-1970",
  },
  {
    audNum:'2m',
    title: "A Chosen Spot (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/a-chosen-spot-part-1/',
    year: "1973",
    date: "January-7-1973",
  },
  {
    audNum:'3m',
    title: "A Chosen Spot (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/a-chosen-spot-part-2/',
    year: "1973",
    date: "January-7-1973",
  },
  {
    audNum:'4m',
    title: "A Cross To Bear",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/a-cross-to-bear/',
    year: "1964",
    date: "April-19-1964",
  },
  {
    audNum:'5m',
    title: "A Drink From The Well Of Bethleham",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/a-drink-from-the-well-of-bethleham/',
    year: "1969",
    date: "December-21-1969",
  },
  {
    audNum:'6m',
    title: "A Dwelling Place For God",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/a-dwelling-place-for-god/',
    year: "1964",
    date: "October-18-1964",
  },
  {
    audNum:'7m',
    title: "A Purpose To Stand (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/a-purpose-to-stand-part-1/',
    year: "1969",
    date: "September-28-1969",
  },
  {
    audNum:'8m',
    title: "A Purpose To Stand (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/a-purpose-to-stand-part-2/',
    year: "1969",
    date: "September-28-1969",
  },
  {
    audNum:'9m',
    title: "A Resting Place For The Ark (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1968",
    date: "December-8-1968",
  },
  {
    audNum:'10m',
    title: "A Resting Place For The Ark (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/a-resting-place-for-the-ark-part-1/',
    year: "1968",
    date: "December-8-1968",
  },
  {
    audNum:'11m',
    title: "A Spiritual Race",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/a-spiritual-race/',
    year: "1964",
    date: "October-11-1964",
  },
  {
    audNum:'12m',
    title: "Abel's Sacrifice",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/abels-sacrifice/',
    year: "1969",
    date: "March-9-1969",
  },
  {
    audNum:'13m',
    title: "Abraham And Lot (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/abraham-and-lot-part-1/',
    year: "1968",
    date: "August-11-1968",
  },
  {
    audNum:'14m',
    title: "Abraham And Lot (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/abraham-and-lot-part-2/',
    year: "1968",
    date: "August-11-1968",
  },
  {
    audNum:'15m',
    title: "Abraham Royal Seed In The Journey (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/abraham-royal-seed-in-the-journey-part-1/',
    year: "1968",
    date: "August-18-1968",
  },
  {
    audNum:'16m',
    title: "Abraham Royal Seed In The Journey (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/all-willing-to-pay-the-price-part-2/',
    year: "1968",
    date: "August-18-1968",
  },
  {
    audNum:'17m',
    title: "All Willing To Pay The Price (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/all-willing-to-pay-the-price-part-1/',
    year: "1970",
    date: "October-4-1970",
  },
  {
    audNum:'18m',
    title: "All Willing To Pay The Price (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/all-willing-to-pay-the-price-part-2/',
    year: "1970",
    date: "October-4-1970",
  },
  {
    audNum:'19m',
    title: "An Open Door",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/an-open-door/',
    year: "1968",
    date: "May-19-1968",
  },
  {
    audNum:'20m',
    title: "An Open Door (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/an-open-door-part-1/',
    year: "1971",
    date: "May-16-1971",
  },
  {
    audNum:'21m',
    title: "An Open Door (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/an-open-door-part-2/',
    year: "1971",
    date: "May-16-1971",
  },
  {
    audNum:'22m',
    title: "An Uncertain Sound",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/an-uncertain-sound/',
    year: "1970",
    date: "October-29-1970",
  },
  {
    audNum:'23m',
    title: "And Israel Abode At Kadesh",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/and-israel-abode-at-kadesh/',
    year: "1969",
    date: "August-14-1969",
  },
  {
    audNum:'24m',
    title: "Apostasy (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/apostasy-part-1/',
    year: "1969",
    date: "March-23-1969",
  },
  {
    audNum:'25m',
    title: "Apostasy (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/apostasy-part-2/',
    year: "1969",
    date: "March-23-1969",
  },
  {
    audNum:'26m',
    title: "Attraction In The Bride (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/attraction-in-the-bride-part-1/',
    year: "1969",
    date: "November-9-1969",
  },
  {
    audNum:'27m',
    title: "Attraction In The Bride (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/attraction-in-the-bride-part-2/',
    year: "1969",
    date: "November-9-1969",
  },
  {
    audNum:'28m',
    title: "Awakening Gods Children",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/awakening-gods-children/',
    year: "1973",
    date: "April-29-1973",
  },
  {
    audNum:'29m',
    title: "Baptism Of The Holy Ghost In Relation To The New Birth (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/baptism-of-the-holy-ghost-in-relation-to-the-new-birth-part-1/',
    year: "1971",
    date: "August-29-1971",
  },
  {
    audNum:'30m',
    title: "Baptism Of The Holy Ghost In Relation To The New Birth (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/baptism-of-the-holy-ghost-in-relation-to-the-new-birth-part-2/',
    year: "1971",
    date: "August-29-1971",
  },
  {
    audNum:'31m',
    title: "Beatitudes",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/beatitudes/',
    year: "1972",
    date: "October-1-1972",
  },
  {
    audNum:'32m',
    title: "Beginning Of Sorrows (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/beginning-of-sorrows-part-1/',
    year: "1970",
    date: "October-11-1970",
  },
  {
    audNum:'33m',
    title: "Beginning Of Sorrows (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/beginning-of-sorrows-part-2/',
    year: "1970",
    date: "October-11-1970",
  },
  {
    audNum:'34m',
    title: "Being Subject",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/being-subject/',
    year: "1965",
    date: "April-14-1965",
  },
  {
    audNum:'35m',
    title: "Believing In Christ",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/believing-in-christ/',
    year: "1971",
    date: "January-17-1971",
  },
  {
    audNum:'36m',
    title: "Bible Prophecy #1 (Rev. 13)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/bible-prophecy-1-rev-13/',
    year: "1973",
    date: "May-27-1973",
  },
  {
    audNum:'37m',
    title: "Bible Prophecy #2 (Rev.)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/bible-prophecy-2-rev/',
    year: "1973",
    date: "May-27-1973",
  },
  {
    audNum:'38m',
    title: "Bible Prophecy #3 (Red Dragon)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/bible-prophecy-3-red-dragon/',
    year: "1973",
    date: "June-3-1973",
  },
  {
    audNum:'39m',
    title: "Bible Prophecy #4 (70 WK)",
    type: "mp3",
    audioUrl:'',
    year: "1973",
    date: "June-10-1973",
  },
  {
    audNum:'40m',
    title: "Bible Prophecy #5 (Two Witnesses)",
    type: "mp3",
    audioUrl:'',
    year: "1973",
    date: "June-10-1973",
  },
  {
    audNum:'41m',
    title: "Bible Prophecy #6 (USA)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/bible-prophecy-4-70-wk/',
    year: "1973",
    date: "July-11-1973",
  },
  {
    audNum:'42m',
    title: "Birthright",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/birthright/',
    year: "1968",
    date: "February-25-1968",
  },
  {
    audNum:'43m',
    title: "Blind Laodicea (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/blind-laodicea-part-1/',
    year: "1968",
    date: "December-8-1968",
  },
  {
    audNum:'44m',
    title: "Blind Laodicea (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/blind-laodicea-part-2/',
    year: "1968",
    date: "December-8-1968",
  },
  {
    audNum:'45m',
    title: "Bride In The Spirit (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/bride-in-the-spirit-part-1/',
    year: "1971",
    date: "June-20-1971",
  },
  {
    audNum:'46m',
    title: "Bride In The Spirit (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/bride-in-the-spirit-part-2/',
    year: "1971",
    date: "June-20-1971",
  },
  {
    audNum:'47m',
    title: "Bro. Bob's Jamaica Trip (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/bro-bobs-jamaica-trip-part-1/',
    year: "1969",
    date: "March-6-1969",
  },
  {
    audNum:'48m',
    title: "Bro. Bob's Jamaica Trip (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/bro-bobs-jamaica-trip-part-2/',
    year: "1969",
    date: "March-6-1969",
  },
  {
    audNum:'49m',
    title: "Bro. Bob's-Robert Lee Lambert's Testimony (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/bro-bobs-robert-lee-lamberts-testimony-part-1/',
    year: "1969",
    date: "January-26-1969",
  },
  {
    audNum:'50m',
    title: "Bro. Bob's-Robert Lee Lambert's Testimony (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/bro-bobs-robert-lee-lamberts-testimony-part-2/',
    year: "1969",
    date: "January-26-1969",
  },
  {
    audNum:'51m',
    title: "Bro. Branham's Heavenly Vision",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/bro-branhams-heavenly-vision/',
    year: "1970",
    date: "August-6-1970",
  },
  {
    audNum:'52m',
    title: "Bro. Robert Lambert's Funeral",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/bro-robert-lamberts-funeral/',
    year: "1973",
    date: "August-6-1973",
  },
  {
    audNum:'53m',
    title: "Broken Fellowship",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/broken-fellowship/',
    year: "1967",
    date: "April-30-1967",
  },
  {
    audNum:'54m',
    title: "Broken Fellowship (New York)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/broken-fellowship-new-york/',
    year: "1964",
    date: "October-21-1964",
  },
  {
    audNum:'55m',
    title: "Building On A Rock",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/building-on-a-rock/',
    year: "1970",
    date: "May-14-1970",
  },
  {
    audNum:'56m',
    title: "Building On Temple Of God (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/building-on-temple-of-god-part-1/',
    year: "1970",
    date: "February-15-1970",
  },
  {
    audNum:'57m',
    title: "Building On Temple Of God (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/building-on-temple-of-god-part-2/',
    year: "1970",
    date: "February-15-1970",
  },
  {
    audNum:'58m',
    title: "By Faith Noah (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/by-faith-noah-part-1/',
    year: "1972",
    date: "February-13-1972",
  },
  {
    audNum:'59m',
    title: "By Faith Noah (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/by-faith-noah-part-2/',
    year: "1972",
    date: "February-13-1972",
  },
  {
    audNum:'60m',
    title: "Calling Upon The Lord To Be Saved (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/calling-upon-the-lord-to-be-saved-part-1/',
    year: "1971",
    date: "September-12-1971",
  },
  {
    audNum:'61m',
    title: "Calling Upon The Lord To Be Saved (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/calling-upon-the-lord-to-be-saved-part-2/',
    year: "1971",
    date: "September-12-1971",
  },
  {
    audNum:'62m',
    title: "Cast Away Your Old Garment",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/cast-away-your-old-garment/',
    year: "1969",
    date: "February-2-1969",
  },
  {
    audNum:'63m',
    title: "Cause Of Wrath Of GOD Today (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/cause-of-wrath-of-god-today-part-1/',
    year: "1971",
    date: "September-19-1971",
  },
  {
    audNum:'64m',
    title: "Cause Of Wrath Of GOD Today (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/cause-of-wrath-of-god-today-part-2/',
    year: "1971",
    date: "September-19-1971",
  },
  {
    audNum:'65m',
    title: "Children Of Disobedience (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/children-of-disobedience-part-1/',
    year: "1970",
    date: "March-15-1970",
  },
  {
    audNum:'66m',
    title: "Children Of Disobedience (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/children-of-disobedience-part-2/',
    year: "1970",
    date: "March-15-1970",
  },
  {
    audNum:'67m',
    title: "Church Age Book (Message To The Church)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/church-age-book-message-to-the-church/',
    year: "1970",
    date: "May-28-1970",
  },
  {
    audNum:'68m',
    title: "Coming Of Christ",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/coming-of-christ/',
    year: "1968",
    date: "June-9-1968",
  },
  {
    audNum:'69m',
    title: "Communion",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/communion/',
    year: "1972",
    date: "April-9-1972",
  },
  {
    audNum:'70m',
    title: "Compel Them To Come In",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/compel-them-to-come-in/',
    year: "1970",
    date: "September-6-1970",
  },
  {
    audNum:'71m',
    title: "Conditioning The Heart To Receive Rev.",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/conditioning-the-heart-to-receive-rev/',
    year: "1972",
    date: "September-24-1972",
  },
  {
    audNum:'72m',
    title: "Contend (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/contend-part-1/',
    year: "1970",
    date: "November-1-1970",
  },
  {
    audNum:'73m',
    title: "Contend (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/contend-part-2/',
    year: "1970",
    date: "November-1-1970",
  },
  {
    audNum:'74m',
    title: "Contend For The Faith",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/contend-for-the-faith/',
    year: "1972",
    date: "February-13-1972",
  },
  {
    audNum:'75m',
    title: "Crossing The Jordan",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/crossing-the-jordan/',
    year: "1967",
    date: "December-17-1967",
  },
  {
    audNum:'76m',
    title: "Crucified In The Place Of A Skull",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/crucified-in-the-place-of-a-skull/',
    year: "1973",
    date: "February-11-1973",
  },
  {
    audNum:'77m',
    title: "David's First Love #1",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/deception-of-satan-part-1/',
    year: "1966",
    date: "December-25-1966",
  },
  {
    audNum:'78m',
    title: "David's First Love #2",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/davids-first-love-2/',
    year: "1966",
    date: "December-25-1966",
  },
  {
    audNum:'79m',
    title: "David's Vision",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/davids-vision/',
    year: "1970",
    date: "September-24-1970",
  },
  {
    audNum:'80m',
    title: "Deception Of Satan (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/deception-of-satan-part-1/',
    year: "1968",
    date: "December-26-1968",
  },
  {
    audNum:'81m',
    title: "Deception Of Satan (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/deception-of-satan-part-2/',
    year: "1968",
    date: "December-26-1968",
  },
  {
    audNum:'82m',
    title: "Deliverance From The Power Of Darkness",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/deliverance-from-the-power-of-darkness/',
    year: "1972",
    date: "March-12-1972",
  },
  {
    audNum:'83m',
    title: "Dreams And Seven Church Ages (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/dreams-and-seven-church-ages-part-1/',
    year: "1969",
    date: "October-9-1969",
  },
  {
    audNum:'84m',
    title: "Dreams And Seven Church Ages (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/dreams-and-seven-church-ages-part-2/',
    year: "1969",
    date: "October-9-1969",
  },
  {
    audNum:'85m',
    title: "Each Step I Take",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/each-step-i-take/',
    year: "1968",
    date: "January-28-1968",
  },
  {
    audNum:'86m',
    title: "Eat, Drink & Be Merry",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/eat-drink-be-merry/',
    year: "1971",
    date: "March-7-1971",
  },
  {
    audNum:'87m',
    title: "Eating All The Lamb",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/eating-all-the-lamb/',
    year: "1967",
    date: "July-5-1967",
  },
  {
    audNum:'88m',
    title: "Elected Lady- Nuggets- Invisible Union (Part 1)",
    type: "mp3",
    audioUrl:'',
    year: "1967",
    date: "November-30-1967",
  },
  {
    audNum:'89m',
    title: "Elected Lady- Nuggets- Invisible Union (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/elected-lady-nuggets-invisible-union-part-2/',
    year: "1967",
    date: "November-30-1967",
  },
  {
    audNum:'90m',
    title: "Election Of Abrahams Royal Seed & Jacob's Ladder",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/election-of-abrahams-royal-seed-jacobs-ladder/',
    year: "1972",
    date: "May-21-1972",
  },
  {
    audNum:'91m',
    title: "Elisha",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/elisha/',
    year: "1970",
    date: "May-24-1970",
  },
  {
    audNum:'92m',
    title: "Empty Vessels (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/empty-vessels-part-1/',
    year: "1969",
    date: "October-19-1969",
  },
  {
    audNum:'93m',
    title: "Empty Vessels (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/empty-vessels-part-2/',
    year: "1969",
    date: "October-19-1969",
  },
  {
    audNum:'94m',
    title: "Endtime Bride Of Christ About Her Father's Business",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/endtime-bride-of-christ-about-her-fathers-business/',
    year: "1970",
    date: "September-6-1970",
  },
  {
    audNum:'95m',
    title: "Ephesians Parallels Joshua #1",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/ephesians-parallels-joshua-1/',
    year: "1972",
    date: "October-1-1972",
  },
  {
    audNum:'96m',
    title: "Ephesians Parallels Joshua #2",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/ephesians-parallels-joshua-2/',
    year: "1972",
    date: "October-8-1972",
  },
  {
    audNum:'97m',
    title: "Ephesians Parallels Joshua #3",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/ephesians-parallels-joshua-3/',
    year: "1972",
    date: "October-8-1972",
  },
  {
    audNum:'98m',
    title: "Ephesians Parallels Joshua #4",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/ephesians-parallels-joshua-4/',
    year: "1972",
    date: "October-15-1972",
  },
  {
    audNum:'99m',
    title: "Ephesians Parallels Joshua #5",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/ephesians-parallels-joshua-5/',
    year: "1972",
    date: "October-15-1972",
  },
  {
    audNum:'100m',
    title: "Ephesians Parallels Joshua #6",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/ephesians-parallels-joshua-6/',
    year: "1973",
    date: "February-11-1973",
  },
  {
    audNum:'101m',
    title: "Evening Light",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/evening-light/',
    year: "1970",
    date: "November-29-1970",
  },
  {
    audNum:'102m',
    title: "Ever Learning - Never Able",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/ever-learning-never-able/',
    year: "1971",
    date: "March-10-1971",
  },
  {
    audNum:'103m',
    title: "Evil Communication (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/evil-communication-part-1/',
    year: "1969",
    date: "June-5-1969",
  },
  {
    audNum:'104m',
    title: "Evil Communication (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/evil-communication-part-2/',
    year: "1969",
    date: "June-5-1969",
  },
  {
    audNum:'105m',
    title: "Evil Heart Of Unbelief",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/evil-heart-of-unbelief/',
    year: "1970",
    date: "April-12-1970",
  },
  {
    audNum:'106m',
    title: "Eye To The Body (Diego Martin, Trinidad) (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/eye-to-the-body-diego-martin-trinidad-part-1/',
    year: "1972",
    date: "December-21-1972",
  },
  {
    audNum:'107m',
    title: "Eye To The Body (Diego Martin, Trinidad) (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/eye-to-the-body-diego-martin-trinidad-part-2/',
    year: "1972",
    date: "December-21-1972",
  },
  {
    audNum:'108m',
    title: "Ezekiel 47",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/ezekiel-47/',
    year: "1970",
    date: "July-12-1970",
  },
  {
    audNum:'109m',
    title: "Faith For The Supernatural Birth (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/faith-for-the-supernatural-birth-part-1/',
    year: "1971",
    date: "October-31-1971",
  },
  {
    audNum:'110m',
    title: "Faith For The Supernatural Birth (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/faith-for-the-supernatural-birth-part-2/',
    year: "1971",
    date: "October-31-1971",
  },
  {
    audNum:'111m',
    title: "Falling Away From The Faith",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/falling-away-from-the-faith/',
    year: "1968",
    date: "May-19-1968",
  },
  {
    audNum:'112m',
    title: "False Christs",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/false-christs/',
    year: "1973",
    date: "April-8-1973",
  },
  {
    audNum:'113m',
    title: "Fasting For Revival",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/fasting-for-revival/',
    year: "1972",
    date: "September-24-1972",
  },
  {
    audNum:'114m',
    title: "Fellowship (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/fellowship-part-1/',
    year: "1971",
    date: "January-3-1971",
  },
  {
    audNum:'115m',
    title: "Fellowship (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/fellowship-part-2/',
    year: "1971",
    date: "January-3-1971",
  },
  {
    audNum:'116m',
    title: "Following Apostolic Pattern",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/following-apostolic-pattern/',
    year: "1967",
    date: "June-25-1967",
  },
  {
    audNum:'117m',
    title:
      "Following The Son Of Man In Regeneration In The Evening Time (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/following-the-son-of-man-in-regeneration-in-the-evening-time-part-2/',
    year: "1970",
    date: "July-12-1970",
  },
  {
    audNum:'118m',
    title:
      "Following The Son Of Man In Regeneration In The Evening Time (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/following-the-son-of-man-in-regeneration-in-the-evening-time-part-2/',
    year: "1970",
    date: "July-12-1970",
  },
  {
    audNum:'119m',
    title: "Foundation Was Laid",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/foundation-was-laid/',
    year: "1967",
    date: "December-10-1967",
  },
  {
    audNum:'120m',
    title: "From Darkness To Light #1",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/from-darkness-to-light-1/',
    year: "1970",
    date: "December-20-1970",
  },
  {
    audNum:'121m',
    title: "From Darkness To Light #2 (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/from-darkness-to-light-2-part-1/',
    year: "1970",
    date: "December-20-1970",
  },
  {
    audNum:'122m',
    title: "From Darkness To Light #2 (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/from-darkness-to-light-2-part-2/',
    year: "1970",
    date: "December-20-1970",
  },
  {
    audNum:'123m',
    title: "Fullness Of Time",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/fullness-of-time/',
    year: "1970",
    date: "August-13-1970",
  },
  {
    audNum:'124m',
    title: "Gathering Together Of Elected (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/gathering-together-of-elected-part-1/',
    year: "1969",
    date: "November-16-1969",
  },
  {
    audNum:'125m',
    title: "Gathering Together Of Elected (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/gathering-together-of-elected-part-2/',
    year: "1969",
    date: "November-16-1969",
  },
  {
    audNum:'126m',
    title: "GOD Creating A Thirst In The Bride",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/god-creating-a-thirst-in-the-bride/',
    year: "1971",
    date: "July-11-1971",
  },
  {
    audNum:'127m',
    title: "GOD Creating A Thirst In The Elected Bride (Jeff, In)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/god-creating-a-thirst-in-the-elected-bride-jeff-ind/',
    year: "1972",
    date: "August-25-1972",
  },
  {
    audNum:'128m',
    title: "God Honors His Word Above His Name",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/god-honors-his-word-above-his-name/',
    year: "1961",
    date: "December-31-1961",
  },
  {
    audNum:'129m',
    title: "GOD Measuring Out The Spirit",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/god-measuring-out-the-spirit/',
    year: "1972",
    date: "May-14-1972",
  },
  {
    audNum:'130m',
    title: "GOD's Faithful Servant (#1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/gods-faithful-servant-1/',
    year: "1972",
    date: "April-9-1972",
  },
  {
    audNum:'131m',
    title: "GOD's Faithful Servant (#2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/gods-faithful-servant-2/',
    year: "1972",
    date: "April-16-1972",
  },
  {
    audNum:'132m',
    title: "GOD'S Unconditional Covenant To The Elected Bride (#1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/gods-unconditional-covenant-to-the-elected-bride-1/',
    year: "1971",
    date: "November-28-1971",
  },
  {
    audNum:'133m',
    title: "GOD'S Unconditional Covenant To The Elected Bride (#2) (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/gods-unconditional-covenant-to-the-elected-bride-2-part-1/',
    year: "1971",
    date: "December-5-1971",
  },
  {
    audNum:'134m',
    title: "GOD'S Unconditional Covenant To The Elected Bride (#2) (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/gods-unconditional-covenant-to-the-elected-bride-2-part-2/',
    year: "1971",
    date: "December-5-1971",
  },
  {
    audNum:'135m',
    title: "GOD'S Unconditional Covenant To The Elected Bride (#3)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/gods-unconditional-covenant-to-the-elected-bride-3/',
    year: "1971",
    date: "December-5-1971",
  },
  {
    audNum:'136m',
    title: "God's Day Of Wrath (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/gods-day-of-wrath-part-1/',
    year: "1968",
    date: "June-23-1968",
  },
  {
    audNum:'137m',
    title: "God's Day Of Wrath (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/gods-day-of-wrath-part-2/',
    year: "1968",
    date: "June-23-1968",
  },
  {
    audNum:'138m',
    title: "God's End Time Sign",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/gods-end-time-sign/',
    year: "1967",
    date: "July-16-1967",
  },
  {
    audNum:'139m',
    title: "God's Gift",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/gods-gift/',
    year: "1967",
    date: "December-17-1967",
  },
  {
    audNum:'140m',
    title: "God's Only Way Of Escape In A Day Of Wrath And Judgment (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/gods-only-way-of-escape-in-a-day-of-wrath-and-judgment-part-1/',
    year: "1969",
    date: "November-23-1969",
  },
  {
    audNum:'141m',
    title: "God's Only Way Of Escape In A Day Of Wrath And Judgment (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/gods-only-way-of-escape-in-a-day-of-wrath-and-judgment-part-2/',
    year: "1969",
    date: "November-23-1969",
  },
  {
    audNum:'142m',
    title: "God's Perfect Love",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/gods-perfect-love/',
    year: "1971",
    date: "February-7-1971",
  },
  {
    audNum:'143m',
    title: "God's Provided Way To Bring Unity (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/gods-provided-way-to-bring-unity-part-1/',
    year: "1969",
    date: "October-12-1969",
  },
  {
    audNum:'144m',
    title: "God's Provided Way To Bring Unity (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/gods-provided-way-to-bring-unity-part-2/',
    year: "1969",
    date: "October-12-1969",
  },
  {
    audNum:'145m',
    title: "God's Sovereign In His Actions",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/gods-sovereign-in-his-actions/',
    year: "1969",
    date: "July-27-1969",
  },
  {
    audNum:'146m',
    title: "Golden Nuggets",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/golden-nuggets/',
    year: "1968",
    date: "August-15-1968",
  },
  {
    audNum:'147m',
    title: "Goodman Of The House",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/goodman-of-the-house/',
    year: "1969",
    date: "April-6-1969",
  },
  {
    audNum:'148m',
    title: "Harvest Time (#1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/harvest-time-1/',
    year: "1972",
    date: "July-29-1972",
  },
  {
    audNum:'149m',
    title: "Harvest Time (#2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/harvest-time-2/',
    year: "1972",
    date: "July-30-1972",
  },
  {
    audNum:'150m',
    title: "Harvest Time (#3)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/harvest-time-3/',
    year: "1972",
    date: "July-30-1972",
  },
  {
    audNum:'151m',
    title: "Hated Because Of Coat Of Many Colors",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/hated-because-of-coat-of-many-colors/',
    year: "1970",
    date: "August-30-1970",
  },
  {
    audNum:'152m',
    title: "He Must Need Go Through Samaria (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/he-must-need-go-through-samaria-part-1/',
    year: "1969",
    date: "October-12-1969",
  },
  {
    audNum:'153m',
    title: "He Must Need Go Through Samaria (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/he-must-need-go-through-samaria-part-2/',
    year: "1969",
    date: "October-12-1969",
  },
  {
    audNum:'154m',
    title: "Hearers Of The Prophet Of Mal 4:5",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/hearers-of-the-prophet-of-mal-45/',
    year: "1970",
    date: "January-4-1970",
  },
  {
    audNum:'155m',
    title: "Hedged In With God",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/hedged-in-with-god/',
    year: "1970",
    date: "February-1-1970",
  },
  {
    audNum:'156m',
    title: "Hour Of Satan's Working",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/hour-of-satans-working/',
    year: "1969",
    date: "September-21-1969",
  },
  {
    audNum:'157m',
    title: "Hour Of Temptation (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/hour-of-temptation-part-1/',
    year: "1970",
    date: "June-14-1970",
  },
  {
    audNum:'158m',
    title: "Hour Of Temptation (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/hour-of-temptation-part-2/',
    year: "1970",
    date: "June-14-1970",
  },
  {
    audNum:'159m',
    title: "How To Be Born Again And How To Enter In (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/how-to-be-born-again-and-how-to-enter-in-part-1/',
    year: "1969",
    date: "March-9-1969",
  },
  {
    audNum:'160m',
    title: "How To Be Born Again And How To Enter In (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/how-to-be-born-again-and-how-to-enter-in-part-2/',
    year: "1969",
    date: "March-9-1969",
  },
  {
    audNum:'161m',
    title: "How To Enter In God's Ark Today (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/how-to-enter-in-gods-ark-today-part-1/',
    year: "1969",
    date: "March-20-1969",
  },
  {
    audNum:'162m',
    title: "How To Enter In God's Ark Today (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/how-to-enter-in-gods-ark-today-part-2/',
    year: "1969",
    date: "March-20-1969",
  },
  {
    audNum:'163m',
    title: "How To Receive The Baptism Of The Holy Ghost",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/how-to-receive-the-baptism-of-the-holy-ghost/',
    year: "1969",
    date: "March-13-1969",
  },
  {
    audNum:'164m',
    title: "Illegitimate Born Children (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/illegitimate-born-children-part-1/',
    year: "1969",
    date: "June-8-1969",
  },
  {
    audNum:'165m',
    title: "Illegitimate Born Children (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/illegitimate-born-children-part-2/',
    year: "1969",
    date: "June-8-1969",
  },
  {
    audNum:'166m',
    title: "Influence",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/influence/',
    year: "1973",
    date: "March-14-1973",
  },
  {
    audNum:'167m',
    title: "Inheritance In Christ (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/inheritance-in-christ-part-1/',
    year: "1970",
    date: "August-9-1970",
  },
  {
    audNum:'168m',
    title: "Inheritance In Christ (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/inheritance-in-christ-part-2/',
    year: "1970",
    date: "August-9-1970",
  },
  {
    audNum:'169m',
    title: "Initial Evidence Of The Holy Ghost",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/initial-evidence-of-the-holy-ghost/',
    year: "1972",
    date: "February-2-1972",
  },
  {
    audNum:'170m',
    title: "Introducing The Messiah",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/introducing-the-messiah/',
    year: "1969",
    date: "July-17-1969",
  },
  {
    audNum:'171m',
    title: "Introduction Of Messiah (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/introduction-of-messiah-part-1/',
    year: "1970",
    date: "August-2-1970",
  },
  {
    audNum:'172m',
    title: "Introduction Of Messiah (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/introduction-of-messiah-part-2/',
    year: "1970",
    date: "August-2-1970",
  },
  {
    audNum:'173m',
    title: "Inviting Jesus Into The Ship",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/inviting-jesus-into-the-ship/',
    year: "1973",
    date: "February-7-1973",
  },
  {
    audNum:'174m',
    title: "Israel Trip",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/israel-trip/',
    year: "1969",
    date: "September-25-1969",
  },
  {
    audNum:'175m',
    title: "Jesus And Peter",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/jesus-and-peter/',
    year: "1969",
    date: "March-16-1969",
  },
  {
    audNum:'176m',
    title: "Joseph",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/joseph/',
    year: "1973",
    date: "January-28-1973",
  },
  {
    audNum:'177m',
    title: "Joy",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/joy/',
    year: "1964",
    date: "April-17-1964",
  },
  {
    audNum:'178m',
    title: "Joy Unspeakable",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/joy-unspeakable/',
    year: "1964",
    date: "April-15-1964",
  },
  {
    audNum:'179m',
    title: "Knowing Your Enemy",
    type: "mp3",
    audioUrl:'',
    year: "1971",
    date: "May-19-1971",
  },
  {
    audNum:'180m',
    title: "Last Separation Before Promise Blessing",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/last-separation-before-promise-blessing/',
    year: "1969",
    date: "April-24-1969",
  },
  {
    audNum:'181m',
    title: "Led By The Spirit",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/led-by-the-spirit/',
    year: "1971",
    date: "May-16-1971",
  },
  {
    audNum:'182m',
    title: "Lesson On Perfect Faith (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/lesson-on-perfect-faith-part-1/',
    year: "1971",
    date: "October-24-1971",
  },
  {
    audNum:'183m',
    title: "Lesson On Perfect Faith (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/lesson-on-perfect-faith-part-2/',
    year: "1971",
    date: "October-24-1971",
  },
  {
    audNum:'184m',
    title: "Liberty",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/liberty/',
    year: "1972",
    date: "September-20-1972",
  },
  {
    audNum:'185m',
    title: "Light",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/light/',
    year: "1973",
    date: "July-8-1973",
  },
  {
    audNum:'186m',
    title: "Living Bread & Body Of The Lord Jesus",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/living-bread-body-of-the-lord-jesus/',
    year: "1968",
    date: "August-4-1968",
  },
  {
    audNum:'187m',
    title: "Living Temple",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/living-temple/',
    year: "1968",
    date: "February-11-1968",
  },
  {
    audNum:'188m',
    title: "Looking For Christ To Come (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/looking-for-christ-to-come-part-1/',
    year: "1970",
    date: "November-8-1970",
  },
  {
    audNum:'189m',
    title: "Looking For Christ To Come (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/looking-for-christ-to-come-part-1/',
    year: "1970",
    date: "November-8-1970",
  },
  {
    audNum:'190m',
    title: "Mal. 3:1-3, 4:5 The Waymaker (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/mal-31-3-45-the-waymaker-part-1/',
    year: "1970",
    date: "June-28-1970",
  },
  {
    audNum:'191m',
    title: "Mal. 3:1-3, 4:5 The Waymaker (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/mal-31-3-45-the-waymaker-part-2/',
    year: "1970",
    date: "June-28-1970",
  },
  {
    audNum:'192m',
    title: "Messages Come To Shepherds-Feed My Sheep",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/messages-come-to-shepherds-feed-my-sheep/',
    year: "1968",
    date: "May-12-1968",
  },
  {
    audNum:'193m',
    title: "Messenger Of The Covenant",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/messenger-of-the-covenant/',
    year: "1968",
    date: "September-29-1968",
  },
  {
    audNum:'194m',
    title: "Ministry Of The Bride #1 (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/ministry-of-the-bride-1-part-1/',
    year: "1972",
    date: "January-2-1972",
  },
  {
    audNum:'195m',
    title: "Ministry Of The Bride #1 (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/ministry-of-the-bride-1-part-2/',
    year: "1972",
    date: "January-2-1972",
  },
  {
    audNum:'196m',
    title: "Ministry Of The Bride #2",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/ministry-of-the-bride-2/',
    year: "1972",
    date: "January-2-1972",
  },
  {
    audNum:'197m',
    title: "Moses` Sin & Smitten Rock (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/moses-sin-smitten-rock-part-1/',
    year: "1969",
    date: "February-2-1969",
  },
  {
    audNum:'198m',
    title: "Moses` Sin & Smitten Rock (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/moses-sin-smitten-rock-part-2/',
    year: "1969",
    date: "February-2-1969",
  },
  {
    audNum:'199m',
    title: "Mystery Of God's Will",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/mystery-of-gods-will/',
    year: "1970",
    date: "May-31-1970",
  },
  {
    audNum:'200m',
    title: "New Year's Eve Service (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/new-years-eve-service-part-1/',
    year: "1970",
    date: "December-31-1970",
  },
  {
    audNum:'201m',
    title: "New Year's Eve Service (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/new-years-eve-service-part-2/',
    year: "1970",
    date: "December-31-1970",
  },
  {
    audNum:'202m',
    title: "No Condemnation To Those In Christ",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/no-condemnation-to-those-in-christ/',
    year: "1971",
    date: "May-2-1971",
  },
  {
    audNum:'203m',
    title: "Nuggets (Bob & Shirleys Dreams Of Mark)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/nuggets-bob-shirleys-dreams-of-mark/',
    year: "1971",
    date: "September-22-1971",
  },
  {
    audNum:'204m',
    title: "Obtaining Mercy And Grace",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/obtaining-mercy-and-grace/',
    year: "1973",
    date: "February-14-1973",
  },
  {
    audNum:'205m',
    title: "Oneness",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/oneness/',
    year: "1968",
    date: "April-21-1968",
  },
  {
    audNum:'206m',
    title: "Our Foundation Today (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/our-foundation-today-part-1/',
    year: "1971",
    date: "January-31-1971",
  },
  {
    audNum:'207m',
    title: "Our Foundation Today (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/our-foundation-today-part-2/',
    year: "1971",
    date: "January-31-1971",
  },
  {
    audNum:'208m',
    title: "Our Redeemer #1",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/our-redeemer-1/',
    year: "1968",
    date: "October-13-1968",
  },
  {
    audNum:'209m',
    title: "Our Redeemer #2",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/our-redeemer-2/',
    year: "1968",
    date: "October-20-1968",
  },
  {
    audNum:'210m',
    title: "Our Redeemer #3 (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/our-redeemer-3-part-1/',
    year: "1968",
    date: "November-3-1968",
  },
  {
    audNum:'211m',
    title: "Our Redeemer #3 (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/our-redeemer-3-part-2/',
    year: "1968",
    date: "November-3-1968",
  },
  {
    audNum:'212m',
    title: "Our Redeemer #4",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/our-redeemer-4/',
    year: "1968",
    date: "November-10-1968",
  },
  {
    audNum:'213m',
    title: "Parable Of The Net",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/parable-of-the-net/',
    year: "1971",
    date: "January-3-1971",
  },
  {
    audNum:'214m',
    title: "Parable Of The Vineyard (#1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/parable-of-the-vineyard-1/',
    year: "1972",
    date: "July-16-1972",
  },
  {
    audNum:'215m',
    title: "Parable Of The Vineyard (#2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/parable-of-the-vineyard-2/',
    year: "1972",
    date: "July-16-1972",
  },
  {
    audNum:'216m',
    title: "Parable On Eleventh Hour Gentile Worker (Jeff, In) (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/parable-on-eleventh-hour-gentile-worker-jeff-in-part-1/',
    year: "1972",
    date: "August-20-1972",
  },
  {
    audNum:'217m',
    title: "Parable On Eleventh Hour Gentile Worker (Jeff, In) (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/parable-on-eleventh-hour-gentile-worker-jeff-in-part-2/',
    year: "1972",
    date: "August-20-1972",
  },
  {
    audNum:'218m',
    title: "Patience (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/patience-part-1/',
    year: "1967",
    date: "November-5-1967",
  },
  {
    audNum:'219m',
    title: "Patience (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/patience-part-2/',
    year: "1967",
    date: "November-5-1967",
  },
  {
    audNum:'220m',
    title: "Patience To Inherit The Promise",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/patience-to-inherit-the-promise/',
    year: "1969",
    date: "July-24-1969",
  },
  {
    audNum:'221m',
    title: "Patience To Wait On God's Promise (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/patience-to-wait-on-gods-promise-part-1/',
    year: "1970",
    date: "March-8-1970",
  },
  {
    audNum:'222m',
    title: "Patience To Wait On God's Promise (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/patience-to-wait-on-gods-promise-part-2/',
    year: "1970",
    date: "March-8-1970",
  },
  {
    audNum:'223m',
    title: "Payday-Payoff (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/payday-payoff-part-1/',
    year: "1971",
    date: "July-25-1971",
  },
  {
    audNum:'224m',
    title: "Payday-Payoff (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/payday-payoff-part-2/',
    year: "1971",
    date: "July-25-1971",
  },
  {
    audNum:'225m',
    title: "Perfection",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/perfection/',
    year: "1968",
    date: "August-18-1968",
  },
  {
    audNum:'226m',
    title: "Perfection (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/perfection-part-1/',
    year: "1970",
    date: "October-25-1970",
  },
  {
    audNum:'227m',
    title: "Perfection (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/perfection-part-2/',
    year: "1970",
    date: "October-25-1970",
  },
  {
    audNum:'228m',
    title: "Persuasion By Influence",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/persuasion-by-influence/',
    year: "1970",
    date: "May-10-1970",
  },
  {
    audNum:'229m',
    title: "Planted By God #1 (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/planted-by-god-1-part-1/',
    year: "1970",
    date: "September-27-1970",
  },
  {
    audNum:'230m',
    title: "Planted By God #1 (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/planted-by-god-1-part-2/',
    year: "1970",
    date: "September-27-1970",
  },
  {
    audNum:'231m',
    title: "Planted By God #2",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/planted-by-god-2/',
    year: "1970",
    date: "September-27-1970",
  },
  {
    audNum:'232m',
    title: "Planted By God #3",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/planted-by-god-3/',
    year: "1970",
    date: "October-1-1970",
  },
  {
    audNum:'233m',
    title: "Positionally Placed Last Time Bride (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/positionally-placed-last-time-bride-part-1/',
    year: "1970",
    date: "May-10-1970",
  },
  {
    audNum:'234m',
    title: "Positionally Placed Last Time Bride (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/positionally-placed-last-time-bride-part-2/',
    year: "1970",
    date: "May-10-1970",
  },
  {
    audNum:'235m',
    title: "Potential",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/potential/',
    year: "1970",
    date: "August-27-1970",
  },
  {
    audNum:'236m',
    title: "Power For Service",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/potential/',
    year: "1970",
    date: "December-6-1970",
  },
  {
    audNum:'237m',
    title: "Power To Loose And Bind",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/power-to-loose-and-bind/',
    year: "1969",
    date: "July-20-1969",
  },
  {
    audNum:'238m',
    title: "Prayer",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/prayer/',
    year: "1969",
    date: "November-5-1969",
  },
  {
    audNum:'239m',
    title: "Preparation For Fulfillment Of The Reveled Promise",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/preparation-for-fulfillment-of-the-reveled-promise/',
    year: "1971",
    date: "April- 25-1971",
  },
  {
    audNum:'240m',
    title: "Proper Doctrine",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/proper-doctrine/',
    year: "1972",
    date: "April- 19-1972",
  },
  {
    audNum:'241m',
    title: "Psalms 91 & 95",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/psalms-91-95/',
    year: "1970",
    date: "June- 25-1970",
  },
  {
    audNum:'242m',
    title: "Questions & Answers #1 (Tree Of Life)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/questions-answers-1-tree-of-life/',
    year: "1971",
    date: "February- 9-1971",
  },
  {
    audNum:'243m',
    title: "Questions & Answers #10",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/questions-answers-10/',
    year: "1972",
    date: "April- 12-1972",
  },
  {
    audNum:'244m',
    title: "Questions & Answers #2",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/questions-answers-2/',
    year: "1971",
    date: "June- 2-1971",
  },
  {
    audNum:'245m',
    title: "Questions & Answers #3",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/questions-answers-3/',
    year: "1971",
    date: "June- 16-1971",
  },
  {
    audNum:'246m',
    title: "Questions & Answers #4",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/questions-answers-4/',
    year: "1971",
    date: "June- 23-1971",
  },
  {
    audNum:'247m',
    title: "Questions & Answers #5",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/questions-answers-5/',
    year: "1971",
    date: "July- 28-1971",
  },
  {
    audNum:'248m',
    title: "Questions & Answers #6 (Bride-Serpent Seed)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/questions-answers-6-bride-serpent-seed/',
    year: "1971",
    date: "August- 14-1971",
  },
  {
    audNum:'249m',
    title: "Questions & Answers #7 ( New Birth )",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/questions-answers-7-new-birth/',
    year: "1971",
    date: "October- 27-1971",
  },
  {
    audNum:'250m',
    title: "Questions & Answers #8",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/questions-answers-8/',
    year: "1972",
    date: "May- 3-1972",
  },
  {
    audNum:'251m',
    title: "Questions & Answers #9",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/questions-answers-9/',
    year: "1972",
    date: "March- 15-1972",
  },
  {
    audNum:'252m',
    title: "Rahab And The Scarlet Cord (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/rahab-and-the-scarlet-cord-part-1/',
    year: "1971",
    date: "August- 29-1971",
  },
  {
    audNum:'253m',
    title: "Rahab And The Scarlet Cord (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/rahab-and-the-scarlet-cord-part-2/',
    year: "1971",
    date: "August- 29-1971",
  },
  {
    audNum:'254m',
    title: "Rapturing Faith (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/rapturing-faith-part-1/',
    year: "1969",
    date: "July- 20-1969",
  },
  {
    audNum:'255m',
    title: "Rapturing Faith (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/rapturing-faith-part-2/',
    year: "1969",
    date: "July- 20-1969",
  },
  {
    audNum:'256m',
    title: "Recongnizing The Promise And Making Preparation For Fulfillment",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/recongnizing-the-promise-and-making-preparation-for-fulfillment/',
    year: "1971",
    date: "June- 27-1971",
  },
  {
    audNum:'257m',
    title: "Redemption By The Blood (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/redemption-by-the-blood-part-1/',
    year: "1970",
    date: "January- 25-1970",
  },
  {
    audNum:'258m',
    title: "Redemption By The Blood (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/redemption-by-the-blood-part-2/',
    year: "1970",
    date: "January- 25-1970",
  },
  {
    audNum:'259m',
    title: "Rejecting God's Council (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/rejecting-gods-council-part-1/',
    year: "1969",
    date: "April- 20-1969",
  },
  {
    audNum:'260m',
    title: "Rejecting God's Council (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/rejecting-gods-council-part-2/',
    year: "1969",
    date: "April- 20-1969",
  },
  {
    audNum:'261m',
    title: "Remarks To The Church",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/remarks-to-the-church/',
    year: "1971",
    date: "September- 5-1971",
  },
  {
    audNum:'262m',
    title: "Remember Lot's Wife (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/remember-lots-wife-part-1/',
    year: "1972",
    date: "June- 4-1972",
  },
  {
    audNum:'263m',
    title: "Remember Lot's Wife (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/remember-lots-wife-part-2/',
    year: "1972",
    date: "June- 4-1972",
  },
  {
    audNum:'264m',
    title: "Reproach For The Word",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/reproach-for-the-word/',
    year: "1969",
    date: "July- 27-1969",
  },
  {
    audNum:'265m',
    title: "Respect To God's Anointed Servants (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/respect-to-gods-anointed-servants-part-1/',
    year: "1970",
    date: "August- 20-1970",
  },
  {
    audNum:'266m',
    title: "Respect To God's Anointed Servants (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/respect-to-gods-anointed-servants-part-2/',
    year: "1970",
    date: "August- 20-1970",
  },
  {
    audNum:'267m',
    title: "Restoration",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/restoration/',
    year: "1968",
    date: "February- 11-1968",
  },
  {
    audNum:'268m',
    title: "Restoration",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/restoration-2/',
    year: "1970",
    date: "May- 3-1970",
  },
  {
    audNum:'269m',
    title: "Rev. Of His Will For Us (#1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/rev-of-his-will-for-us-1/',
    year: "1972",
    date: "December- 26-1972",
  },
  {
    audNum:'270m',
    title: "Rev. Of His Will For Us (#2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/rev-of-his-will-for-us-2/',
    year: "1972",
    date: "December- 26-1972",
  },
  {
    audNum:'271m',
    title: "Rev. Of The Son Of Man",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/rev-of-the-son-of-man/',
    year: "1968",
    date: "January- 28-1968",
  },
  {
    audNum:'272m',
    title: "Rich & Have Need Of Nothing",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/rich-have-need-of-nothing/',
    year: "1968",
    date: "January- 21-1968",
  },
  {
    audNum:'273m',
    title: "Righteousness & Justification #1",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/righteousness-justification-1/',
    year: "1970",
    date: "July- 9-1970",
  },
  {
    audNum:'274m',
    title: "Righteousness & Justification #2",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/righteousness-justification-2/',
    year: "1970",
    date: "July- 23-1970",
  },
  {
    audNum:'275m',
    title: "Rivers Of Unbelief & Bride Out Of Step (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/rivers-of-unbelief-bride-out-of-step-part-1/',
    year: "1968",
    date: "January- 14-1968",
  },
  {
    audNum:'276m',
    title: "Rivers Of Unbelief & Bride Out Of Step (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/rivers-of-unbelief-bride-out-of-step-part-2/',
    year: "1968",
    date: "January- 14-1968",
  },
  {
    audNum:'277m',
    title: "Salt Without Savour",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/salt-without-savour/',
    year: "1968",
    date: "August- 11-1968",
  },
  {
    audNum:'278m',
    title: "Satan And Job (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/satan-and-job-part-1/',
    year: "1969",
    date: "September- 21-1969",
  },
  {
    audNum:'279m',
    title: "Satan And Job (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/satan-and-job-part-2/',
    year: "1969",
    date: "September- 21-1969",
  },
  {
    audNum:'280m',
    title: "Scoffers Of The Promise",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/scoffers-of-the-promise/',
    year: "1971",
    date: "January- 7-1971",
  },
  {
    audNum:'281m',
    title: "Second Hand Religion",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/second-hand-religion/',
    year: "1972",
    date: "May- 14-1972",
  },
  {
    audNum:'282m',
    title: "Seeking Love",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/seeking-love/',
    year: "1973",
    date: "April- 8-1973",
  },
  {
    audNum:'283m',
    title: "Seeking The Lord For Revival",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/seeking-the-lord-for-revival/',
    year: "1972",
    date: "September- 9-1972",
  },
  {
    audNum:'284m',
    title: "Seeking To Find Jesus (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/seeking-to-find-jesus-part-1/',
    year: "1969",
    date: "April- 6-1969",
  },
  {
    audNum:'285m',
    title: "Seeking To Find Jesus (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/seeking-to-find-jesus-part-2/',
    year: "1969",
    date: "April- 6-1969",
  },
  {
    audNum:'286m',
    title: "Shamgar",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/shamgar/',
    year: "1968",
    date: "October- 20-1968",
  },
  {
    audNum:'287m',
    title: "Sleepless Prayer",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/sleepless-prayer/',
    year: "1964",
    date: "October- 14-1964",
  },
  {
    audNum:'288m',
    title: "Some Standing Here",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/some-standing-here/',
    year: "1970",
    date: "December- 3-1970",
  },
  {
    audNum:'289m',
    title: "Something You Can Do",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/something-you-can-do/',
    year: "1973",
    date: "April- 25-1973",
  },
  {
    audNum:'290m',
    title: "Son Of Man (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/son-of-man-part-1/',
    year: "1970",
    date: "June- 21-1970",
  },
  {
    audNum:'291m',
    title: "Son Of Man (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/son-of-man-part-2/',
    year: "1970",
    date: "June- 21-1970",
  },
  {
    audNum:'292m',
    title: "Son Of Man And His Angels #1 (Jeff, In) (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/son-of-man-and-his-angels-1-jeff-in-part-1/',
    year: "1973",
    date: "January- 20-1973",
  },
  {
    audNum:'293m',
    title: "Son Of Man And His Angels #1 (Jeff, In) (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/son-of-man-and-his-angels-1-jeff-in-part-2/',
    year: "1973",
    date: "January- 20-1973",
  },
  {
    audNum:'294m',
    title: "Son Of Man And His Angels #2 (Jeff, In)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/son-of-man-and-his-angels-2-jeff-in/',
    year: "1973",
    date: "January- 21-1973",
  },
  {
    audNum:'295m',
    title: "Son Of Man And The Little Book (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/son-of-man-and-the-little-book-part-1/',
    year: "1971",
    date: "March- 21-1971",
  },
  {
    audNum:'296m',
    title: "Son Of Man And The Little Book (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/son-of-man-and-the-little-book-part-2/',
    year: "1971",
    date: "March- 21-1971",
  },
  {
    audNum:'297m',
    title: "Son Of Man Ministry",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/son-of-man-ministry/',
    year: "1972",
    date: "June- 28-1972",
  },
  {
    audNum:'298m',
    title: "Son's Back To Eden",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/sons-back-to-eden/',
    year: "1967",
    date: "August- 10-1967",
  },
  {
    audNum:'299m',
    title: "Sound Doctrine (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/sound-doctrine-part-1/',
    year: "1968",
    date: "June- 2-1968",
  },
  {
    audNum:'300m',
    title: "Sound Doctrine (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/sound-doctrine-part-2/',
    year: "1968",
    date: "June- 2-1968",
  },
  {
    audNum:'301m',
    title: "Spirit Of Christ",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/spirit-of-christ/',
    year: "1968",
    date: "June- 30-1968",
  },
  {
    audNum:'302m',
    title: "Spirit Of Elijah (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/spirit-of-elijah-part-1/',
    year: "1968",
    date: "June- 16-1968",
  },
  {
    audNum:'303m',
    title: "Spirit Of Elijah (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/spirit-of-elijah-part-2/',
    year: "1968",
    date: "June- 16-1968",
  },
  {
    audNum:'304m',
    title: "Spirit Of Moses (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/spirit-of-moses-part-1/',
    year: "1968",
    date: "June- 23-1968",
  },
  {
    audNum:'305m',
    title: "Spirit Of Moses (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/spirit-of-moses-part-2/',
    year: "1968",
    date: "June- 23-1968",
  },
  {
    audNum:'306m',
    title: "Spirit Of The Son Of Man",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/spirit-of-the-son-of-man/',
    year: "1968",
    date: "July- 7-1968",
  },
  {
    audNum:'307m',
    title: "Spiritual Cancer",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/spiritual-cancer/',
    year: "1967",
    date: "August- 3-1967",
  },
  {
    audNum:'308m',
    title: "Spoken Word Original Seed #1 (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/spoken-word-original-seed-part-1/',
    year: "1971",
    date: "May- 23-1971",
  },
  {
    audNum:'309m',
    title: "Spoken Word Original Seed #1 (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/spoken-word-original-seed-part-2/',
    year: "1971",
    date: "May- 23-1971",
  },
  {
    audNum:'310m',
    title: "Spoken Word Original Seed #2",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/spoken-word-original-seed-2/',
    year: "1971",
    date: "May- 23-1971",
  },
  {
    audNum:'311m',
    title: "Spoken Word Original Seed #3 (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/spoken-word-original-seed-3-part-1/',
    year: "1971",
    date: "July- 18-1971",
  },
  {
    audNum:'312m',
    title: "Spoken Word Original Seed #3 (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/spoken-word-original-seed-3-part-2/',
    year: "1971",
    date: "July- 18-1971",
  },
  {
    audNum:'313m',
    title: "Spoken Word Original Seed #4 (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/spoken-word-original-seed-4-part-1/',
    year: "1971",
    date: "August- 8-1971",
  },
  {
    audNum:'314m',
    title: "Spoken Word Original Seed #4 (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/spoken-word-original-seed-4-part-2/',
    year: "1971",
    date: "August- 8-1971",
  },
  {
    audNum:'315m',
    title: "Study-Christ The Mystery Of God Revealed (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/study-christ-the-mystery-of-god-revealed-part/',
    year: "1968",
    date: "November- 24-1968",
  },
  {
    audNum:'316m',
    title: "Study-Christ The Mystery Of God Revealed (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/study-christ-the-mystery-of-god-revealed-part-2/',
    year: "1968",
    date: "November- 24-1968",
  },
  {
    audNum:'317m',
    title: "Substitute (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/substitute-part-1/',
    year: "1969",
    date: "June- 15-1969",
  },
  {
    audNum:'318m',
    title: "Substitute (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/substitute-part-2/',
    year: "1969",
    date: "June- 15-1969",
  },
  {
    audNum:'319m',
    title: "Sun Of Righteousness",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/sun-of-righteousness/',
    year: "1972",
    date: "July- 9-1972",
  },
  {
    audNum:'320m',
    title: "Take Heed How You Hear (Durham, CT)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/take-heed-how-you-hear-durham-ct/',
    year: "1972",
    date: "March- 19-1972",
  },
  {
    audNum:'321m',
    title: "Take Heed How You Hear (Jeff, In)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/take-heed-how-you-hearjeff-in/',
    year: "1972",
    date: "August- 26-1972",
  },
  {
    audNum:'322m',
    title: "Tape-One More Time WMB, R. Lambert (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/tape-one-more-time-wmb-r-lambert-part-2/',
    year: "1971",
    date: "January- 17-1971",
  },
  {
    audNum:'323m',
    title: "Tape-One More Time WMB, R. Lambert (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/tape-one-more-time-wmb-r-lambert-part-2/',
    year: "1971",
    date: "January- 17-1971",
  },
  {
    audNum:'324m',
    title: "Tape-Testing Time-WMB",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/tape-testing-time-wmb/',
    year: "1971",
    date: "January- 31-1971",
  },
  {
    audNum:'325m',
    title: "Tender Mercies Of GOD",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/tender-mercies-of-god/',
    year: "1972",
    date: "April- 16-1972",
  },
  {
    audNum:'326m',
    title: "Testing Before Blessing",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/tender-mercies-of-god/',
    year: "1968",
    date: "February- 4-1968",
  },
  {
    audNum:'327m',
    title: "Testing For Discipleship By The Revealed Word",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/testing-for-discipleship-by-the-revealed-word/',
    year: "1971",
    date: "August- 11-1971",
  },
  {
    audNum:'328m',
    title: "The Blood Speaks (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-blood-speaks-part-1/',
    year: "1972",
    date: "January- 30-1972",
  },
  {
    audNum:'329m',
    title: "The Blood Speaks (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-blood-speaks-part-2/',
    year: "1972",
    date: "January- 30-1972",
  },
  {
    audNum:'330m',
    title: "The Capstone",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-capstone/',
    year: "1972",
    date: "September- 16-1972",
  },
  {
    audNum:'331m',
    title: "The Cares Of This Life",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-cares-of-this-life/',
    year: "1968",
    date: "November- 10-1968",
  },
  {
    audNum:'332m',
    title: "The Coming Of The King",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-coming-of-the-king/',
    year: "1972",
    date: "December- 6-1972",
  },
  {
    audNum:'333m',
    title: "The Cup Of Salvation #1 (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-cup-of-salvation-1-part-1/',
    year: "1970",
    date: "November- 15-1970",
  },
  {
    audNum:'334m',
    title: "The Cup Of Salvation #1 (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-cup-of-salvation-1-part-2/',
    year: "1970",
    date: "November- 15-1970",
  },
  {
    audNum:'335m',
    title: "The Cup Of Salvation #2",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-cup-of-salvation-2/',
    year: "1970",
    date: "November- 15-1970",
  },
  {
    audNum:'336m',
    title: "The Days Of Noe (Last Message Preached)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-days-of-noe-last-message-preached/',
    year: "1973",
    date: "August- 1-1973",
  },
  {
    audNum:'337m',
    title: "The Divine Sculptor's Masterpiece",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-divine-sculptors-masterpiece/',
    year: "1968",
    date: "May- 26-1968",
  },
  {
    audNum:'338m',
    title: "The Eunuchs Of The Lord Jesus Christ",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/01-the-eunuchs-of-the-lord-jesus-christ/',
    year: "1966",
    date: "April- 1-1966",
  },
  {
    audNum:'339m',
    title: "The Evil Nature",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-evil-nature/',
    year: "1964",
    date: "October- 11-1964",
  },
  {
    audNum:'340m',
    title: "The Eye To The Body (Jeff, In)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-eye-to-the-body-jeff-in/',
    year: "1972",
    date: "August- 20-1972",
  },
  {
    audNum:'341m',
    title: "The Eyes Of The Lord (In Relation To The Body Of Christ)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-eyes-of-the-lord-in-relation-to-the-body-of-christ/',
    year: "1971",
    date: "October- 3-1971",
  },
  {
    audNum:'342m',
    title: "The Friend Of The Bridegroom",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-friend-of-the-bridegroom/',
    year: "1970",
    date: "April- 12-1970",
  },
  {
    audNum:'343m',
    title: "The Godhead",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-godhead/',
    year: "1969",
    date: "October- 30-1969",
  },
  {
    audNum:'344m',
    title: "The Good Samaritan",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-good-samaritan/',
    year: "1967",
    date: "July- 30-1967",
  },
  {
    audNum:'345m',
    title: "The Great Physician (In Relation To Pregnancy & Birth) (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-great-physician-in-relation-to-pregnancy-birth-part-1/',
    year: "1971",
    date: "January- 24-1971",
  },
  {
    audNum:'346m',
    title: "The Great Physician (In Relation To Pregnancy & Birth) (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-great-physician-in-relation-to-pregnancy-birth-part-2/',
    year: "1971",
    date: "January- 24-1971",
  },
  {
    audNum:'347m',
    title: "The Great Whore (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-great-whore-part-1/',
    year: "1969",
    date: "October- 19-1969",
  },
  {
    audNum:'348m',
    title: "The Great Whore (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-great-whore-part-2/',
    year: "1969",
    date: "October- 19-1969",
  },
  {
    audNum:'349m',
    title: "The Great Word Test",
    type: "mp3",
    audioUrl:'',
    year: "1972",
    date: "June- 4-1972",
  },
  {
    audNum:'350m',
    title: "The Great Word Test (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-great-word-test/',
    year: "1971",
    date: "March- 7-1971",
  },
  {
    audNum:'351m',
    title: "The Great Word Test (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-great-word-test-part-1/',
    year: "1971",
    date: "March- 7-1971",
  },
  {
    audNum:'352m',
    title: "The Hardening Heart",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-hardening-heart/',
    year: "1968",
    date: "February- 18-1968",
  },
  {
    audNum:'353m',
    title: "The Hireling Shepherd",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-hireling-shepherd/',
    year: "1965",
    date: "April- 11-1965",
  },
  {
    audNum:'354m',
    title: "The Image Of The Invisible GOD",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-image-of-the-invisible-god/',
    year: "1971",
    date: "November- 21-1971",
  },
  {
    audNum:'355m',
    title: "The Invisible GOD Made Visible",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-invisible-god-made-visible/',
    year: "1971",
    date: "October- 31-1971",
  },
  {
    audNum:'356m',
    title: "The Kingdom Is Rent From Thee (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-kingdom-is-rent-from-thee-part-1/',
    year: "1968",
    date: "November- 17-1968",
  },
  {
    audNum:'357m',
    title: "The Kingdom Is Rent From Thee (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-kingdom-is-rent-from-thee-part-2/',
    year: "1968",
    date: "November- 17-1968",
  },
  {
    audNum:'358m',
    title: "The Last Day Ministry",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-last-day-ministry/',
    year: "1965",
    date: "October- 15-1965",
  },
  {
    audNum:'359m',
    title: "The Latter Rain",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-latter-rain/',
    year: "1971",
    date: "July- 11-1971",
  },
  {
    audNum:'360m',
    title: "The Lightning Of The Candle",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-lightning-of-the-candle/',
    year: "1971",
    date: "June- 27-1971",
  },
  {
    audNum:'361m',
    title: "The Lost Capstone",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-lost-capstone/',
    year: "1972",
    date: "September- 17-1972",
  },
  {
    audNum:'362m',
    title: "The Man Child",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-man-child/',
    year: "1972",
    date: "October- 22-1972",
  },
  {
    audNum:'363m',
    title: "The Man-Child Made Manifested In This Hour",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-man-child-made-manifested-in-this-hour/',
    year: "1966",
    date: "August- 13-1966",
  },
  {
    audNum:'364m',
    title: "The Mind Of Christ",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-mind-of-christ/',
    year: "1967",
    date: "January- 1-1967",
  },
  {
    audNum:'365m',
    title: "The Ministry Of The Bride",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-ministry-of-the-bride/',
    year: "1967",
    date: "April- 23-1967",
  },
  {
    audNum:'366m',
    title: "The Perfect Word For The Perfect Day (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-perfect-word-for-the-perfect-day-part-1/',
    year: "1971",
    date: "February- 7-1971",
  },
  {
    audNum:'367m',
    title: "The Perfect Word For The Perfect Day (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-perfect-word-for-the-perfect-day-part-2/',
    year: "1971",
    date: "February- 7-1971",
  },
  {
    audNum:'368m',
    title: "The Return Of The Same Jesus (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-return-of-the-same-jesus-part-1/',
    year: "1971",
    date: "August- 22-1971",
  },
  {
    audNum:'369m',
    title: "The Return Of The Same Jesus (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-return-of-the-same-jesus-part-2/',
    year: "1971",
    date: "August- 22-1971",
  },
  {
    audNum:'370m',
    title: "The Things Concerning Himself",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-things-concerning-himself/',
    year: "1973",
    date: "May- 30-1973",
  },
  {
    audNum:'371m',
    title: "The Token (#1) (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-token-1-part-1/',
    year: "1970",
    date: "March- 22-1970",
  },
  {
    audNum:'372m',
    title: "The Token (#1) (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-token-1-part-2/',
    year: "1970",
    date: "March- 22-1970",
  },
  {
    audNum:'373m',
    title: "The Token (#2) (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-token-2-part-1/',
    year: "1970",
    date: "March- 22-1970",
  },
  {
    audNum:'374m',
    title: "The Token (#2) (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-token-2-part-2/',
    year: "1970",
    date: "March- 22-1970",
  },
  {
    audNum:'375m',
    title: "The Token Nuggets (#1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-token-nuggets-1/',
    year: "1972",
    date: "July- 23-1972",
  },
  {
    audNum:'376m',
    title: "The Token Nuggets (#2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-token-nuggets-2/',
    year: "1972",
    date: "July- 23-1972",
  },
  {
    audNum:'377m',
    title: "The Truth Shall Make You Free (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-truth-shall-make-you-free-part-1/',
    year: "1971",
    date: "February- 28-1971",
  },
  {
    audNum:'378m',
    title: "The Truth Shall Make You Free (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-truth-shall-make-you-free-part-2/',
    year: "1971",
    date: "February- 28-1971",
  },
  {
    audNum:'379m',
    title: "The Vision Today",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-vision-today/',
    year: "1971",
    date: "August- 22-1971",
  },
  {
    audNum:'380m',
    title: "The Voice Of The Archangel",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-voice-of-the-archangel/',
    year: "1970",
    date: "November- 22-1970",
  },
  {
    audNum:'381m',
    title: "The Voice Of The Archangel #1 (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-voice-of-the-archangel-1-part-1/',
    year: "1973",
    date: "January- 14-1973",
  },
  {
    audNum:'382m',
    title: "The Voice Of The Archangel #1 (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-voice-of-the-archangel-1-part-2/',
    year: "1973",
    date: "January- 14-1973",
  },
  {
    audNum:'383m',
    title: "The Voice Of The Archangel #2",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-voice-of-the-archangel-2/',
    year: "1973",
    date: "January- 14-1973",
  },
  {
    audNum:'384m',
    title: "The Voice That Catches The Bride (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-voice-that-catches-the-bride-part-1/',
    year: "1970",
    date: "November- 22-1970",
  },
  {
    audNum:'385m',
    title: "The Voice That Catches The Bride (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-voice-that-catches-the-bride-part-2/',
    year: "1970",
    date: "November- 22-1970",
  },
  {
    audNum:'386m',
    title: "The Way Of Salvation",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-way-of-salvation/',
    year: "1970",
    date: "November- 8-1970",
  },
  {
    audNum:'387m',
    title: "The Word Of His Patience",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/the-word-of-his-patience/',
    year: "1973",
    date: "May- 23-1973",
  },
  {
    audNum:'388m',
    title: "Things Reproved Are Made Manifested",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/things-reproved-are-made-manifested/',
    year: "1970",
    date: "October- 4-1970",
  },
  {
    audNum:'389m',
    title: "Tormenting The Ungodly (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/tormenting-the-ungodly-part-1/',
    year: "1968",
    date: "November- 17-1968",
  },
  {
    audNum:'390m',
    title: "Tormenting The Ungodly (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/tormenting-the-ungodly-part-2/',
    year: "1968",
    date: "November- 17-1968",
  },
  {
    audNum:'391m',
    title: "Trinidad Service",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/trinidad-service/',
    year: "1972",
    date: "December- 23-1972",
  },
  {
    audNum:'392m',
    title: 'Trinidad Service "Son Of Man" (Part 1)',
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/trinidad-service-son-of-man-part-1/',
    year: "1972",
    date: "December- 24-1972",
  },
  {
    audNum:'393m',
    title: 'Trinidad Service "Son Of Man" (Part 2)',
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/trinidad-service-son-of-man-part-2/',
    year: "1972",
    date: "December- 24-1972",
  },
  {
    audNum:'394m',
    title: "Trinidad Trip & Ministers Testimonies",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/trinidad-trip-ministers-testimonies/',
    year: "1972",
    date: "January- 19-1972",
  },
  {
    audNum:'395m',
    title: "Troubling Of Waters",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/troubling-of-waters/',
    year: "1970",
    date: "November- 1-1970",
  },
  {
    audNum:'396m',
    title: "True Atonement (Christ Rev. From Heaven) (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/true-atonement-christ-rev-from-heaven-part-1/',
    year: "1972",
    date: "May- 7-1972",
  },
  {
    audNum:'397m',
    title: "True Atonement (Christ Rev. From Heaven) (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/true-atonement-christ-rev-from-heaven-part-2/',
    year: "1972",
    date: "May- 7-1972",
  },
  {
    audNum:'398m',
    title: "True Church",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/true-church/',
    year: "1970",
    date: "April- 23-1970",
  },
  {
    audNum:'399m',
    title: "Trumpet Of Jubilee (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/trumpet-of-jubilee-part-1/',
    year: "1969",
    date: "March- 16-1969",
  },
  {
    audNum:'400m',
    title: "Trumpet Of Jubilee (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/trumpet-of-jubilee-part-2/',
    year: "1969",
    date: "March- 16-1969",
  },
  {
    audNum:'401m',
    title: "Truth",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/truth/',
    year: "1973",
    date: "May- 6-1973",
  },
  {
    audNum:'402m',
    title: "Two Great Women And Their Reward",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/two-great-women-and-their-reward/',
    year: "1967",
    date: "December- 10-1967",
  },
  {
    audNum:'403m',
    title: "Two Kingdoms #1 (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/two-kingdoms-1-part-1/',
    year: "1970",
    date: "September- 13-1970",
  },
  {
    audNum:'404m',
    title: "Two Kingdoms #1 (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/two-kingdoms-1-part-2/',
    year: "1970",
    date: "September- 13-1970",
  },
  {
    audNum:'405m',
    title: "Two Kingdoms #2 (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/two-kingdoms-2-part-1/',
    year: "1970",
    date: "September- 13-1970",
  },
  {
    audNum:'406m',
    title: "Two Kingdoms #2 (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/two-kingdoms-2-part-2/',
    year: "1970",
    date: "September- 13-1970",
  },
  {
    audNum:'407m',
    title: "Two Kingdoms #3 (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/two-kingdoms-3-part-1/',
    year: "1970",
    date: "September- 14-1970",
  },
  {
    audNum:'408m',
    title: "Two Kingdoms #3 (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/two-kingdoms-3-part-2/',
    year: "1970",
    date: "September- 14-1970",
  },
  {
    audNum:'409m',
    title: "Two Kingdoms #4 (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/two-kingdoms-4-part-1/',
    year: "1971",
    date: "April- 11-1971",
  },
  {
    audNum:'410m',
    title: "Two Kingdoms #4 (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/two-kingdoms-4-part-2/',
    year: "1971",
    date: "April- 11-1971",
  },
  {
    audNum:'411m',
    title: "Two Kingdoms #5 (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/two-kingdoms-5-part-1/',
    year: "1970",
    date: "April- 18-1970",
  },
  {
    audNum:'412m',
    title: "Two Kingdoms #5 (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/two-kingdoms-5-part-2/',
    year: "1970",
    date: "April- 18-1970",
  },
  {
    audNum:'413m',
    title: "Two Kingdoms #6 (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/two-kingdoms-6-part-1/',
    year: "1971",
    date: "April- 18-1971",
  },
  {
    audNum:'414m',
    title: "Two Kingdoms #6 (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/two-kingdoms-6-part-2/',
    year: "1971",
    date: "April- 18-1971",
  },
  {
    audNum:'415m',
    title: "Two Trees In Eden (#1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/two-trees-in-eden-1/',
    year: "1973",
    date: "March- 18-1973",
  },
  {
    audNum:'416m',
    title: "Two Trees In Eden (#2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/two-trees-in-eden-2/',
    year: "1973",
    date: "March- 18-1973",
  },
  {
    audNum:'417m',
    title: "Unclean Spirits Like Frogs (#1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/unclean-spirits-like-frogs-1/',
    year: "1972",
    date: "August- 6-1972",
  },
  {
    audNum:'418m',
    title: "Unclean Spirits Like Frogs (#2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/unclean-spirits-like-frogs-2/',
    year: "1972",
    date: "August- 6-1972",
  },
  {
    audNum:'419m',
    title: "Vain Jangling",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/vain-jangling/',
    year: "1969",
    date: "July- 25-1969",
  },
  {
    audNum:'420m',
    title: "Villa Capri",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/villa-capri/',
    year: "1961",
    date: "July- 22-1961",
  },
  {
    audNum:'421m',
    title: "Walking In The Light With Eye Single",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/walking-in-the-light-with-eye-single/',
    year: "1971",
    date: "September- 19-1971",
  },
  {
    audNum:'422m',
    title: "Walking On The Water",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/walking-on-the-water/',
    year: "1969",
    date: "November- 9-1969",
  },
  {
    audNum:'423m',
    title: "Wandering Thoughts",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/wandering-thoughts/',
    year: "1969",
    date: "February- 6-1969",
  },
  {
    audNum:'424m',
    title: "Wedding Garment",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/wedding-garment/',
    year: "1970",
    date: "February- 15-1970",
  },
  {
    audNum:'425m',
    title: "What Price Token #1 (Pearl Of Great Price)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/what-price-token-1-pearl-of-great-price/',
    year: "1970",
    date: "August- 23-1970",
  },
  {
    audNum:'426m',
    title: "What Price Token #2 (Parable Of The Net)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/what-price-token-2-parable-of-the-net/',
    year: "1970",
    date: "August- 23-1970",
  },
  {
    audNum:'427m',
    title: "What's Upon My Heart #1 (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/whats-upon-my-heart-1-part-1/',
    year: "1969",
    date: "April- 27-1969",
  },
  {
    audNum:'428m',
    title: "What's Upon My Heart #1 (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/whats-upon-my-heart-1-part-1/',
    year: "1969",
    date: "April- 27-1969",
  },
  {
    audNum:'429m',
    title: "What's Upon My Heart #2 (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/whats-upon-my-heart-2-part-1/',
    year: "1969",
    date: "April- 27-1969",
  },
  {
    audNum:'430m',
    title: "What's Upon My Heart #2 (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/whats-upon-my-heart-2-part-2/',
    year: "1969",
    date: "April- 27-1969",
  },
  {
    audNum:'431m',
    title: "Who Can Be Saved",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/who-can-be-saved/',
    year: "1971",
    date: "February- 28-1971",
  },
  {
    audNum:'432m',
    title: "Who Gets The Token In The Endtime",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/who-gets-the-token-in-the-endtime/',
    year: "1971",
    date: "January- 14-1971",
  },
  {
    audNum:'433m',
    title: "Who Hath Believed Our Report (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/who-hath-believed-our-report-part-1/',
    year: "1968",
    date: "September- 29-1968",
  },
  {
    audNum:'434m',
    title: "Who Hath Believed Our Report (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/who-hath-believed-our-report-part-2/',
    year: "1968",
    date: "September- 29-1968",
  },
  {
    audNum:'435m',
    title: "Who Hath Belived Our Report (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/who-hath-belived-our-report-part-1/',
    year: "1971",
    date: "March- 14-1971",
  },
  {
    audNum:'436m',
    title: "Who Hath Belived Our Report (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/who-hath-belived-our-report-part-2/',
    year: "1971",
    date: "March- 14-1971",
  },
  {
    audNum:'437m',
    title: "Who Understandeth God",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/who-understandeth-god/',
    year: "1970",
    date: "October- 8-1970",
  },
  {
    audNum:'438m',
    title: "Why Did God Hate Esau (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/why-did-god-hate-esau-part-1/',
    year: "1969",
    date: "October- 26-1969",
  },
  {
    audNum:'439m',
    title: "Why Did God Hate Esau (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/why-did-god-hate-esau-part-2/',
    year: "1969",
    date: "October- 26-1969",
  },
  {
    audNum:'440m',
    title: "Why God Hated Esau",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/why-god-hated-esau/',
    year: "1973",
    date: "January- 28-1973",
  },
  {
    audNum:'441m',
    title: "Why Is Christ Rejected Today",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/why-is-christ-rejected-today/',
    year: "1970",
    date: "September- 3-1970",
  },
  {
    audNum:'442m',
    title: "Why Judas Was Not Saved",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/why-judas-was-not-saved/',
    year: "1971",
    date: "December- 22-1971",
  },
  {
    audNum:'443m',
    title: "Why Our Prayers Not Answered",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/why-our-prayers-not-answered/',
    year: "1971",
    date: "November- 21-1971",
  },
  {
    audNum:'444m',
    title: "Woman At The Well (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/woman-at-the-well-part-1/',
    year: "1971",
    date: "May- 3-1971",
  },
  {
    audNum:'445m',
    title: "Woman At The Well (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/woman-at-the-well-part-2/',
    year: "1971",
    date: "May- 3-1971",
  },
  {
    audNum:'446m',
    title: "Woman At The Well (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/woman-at-the-well-part-1-2/',
    year: "1970",
    date: "May- 3-1970",
  },
  {
    audNum:'447m',
    title: "Woman At The Well (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/woman-at-the-well-part-2-2/',
    year: "1970",
    date: "May- 3-1970",
  },
  {
    audNum:'448m',
    title: "Women At The Well",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/women-at-the-well/',
    year: "1972",
    date: "May- 28-1972",
  },
  {
    audNum:'449m',
    title: "Word Atonement For The Bride (#1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/word-atonement-for-the-bride-1/',
    year: "1972",
    date: "January- 23-1972",
  },
  {
    audNum:'450m',
    title: "Word Atonement For The Bride (#2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/word-atonement-for-the-bride-2/',
    year: "1972",
    date: "January- 23-1972",
  },
  {
    audNum:'451m',
    title: "Word Atonement For The Bride (#3)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/word-atonement-for-the-bride-3/',
    year: "1972",
    date: "January- 26-1972",
  },
  {
    audNum:'452m',
    title: "Word Of Promise (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/word-of-promise-part-1/',
    year: "1970",
    date: "February- 8-1970",
  },
  {
    audNum:'453m',
    title: "Word Of Promise (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/word-of-promise-part-2/',
    year: "1970",
    date: "February- 8-1970",
  },
  {
    audNum:'454m',
    title: "Your Adversary",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/your-adversary/',
    year: "1971",
    date: "January- 28-1971",
  },
  {
    audNum:'455m',
    title: "Your Revelation Is The Victory (Part 1)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/your-revelation-is-the-victory-part-1/',
    year: "1969",
    date: "October- 26-1969",
  },
  {
    audNum:'456m',
    title: "Your Revelation Is The Victory (Part 2)",
    type: "mp3",
    audioUrl:'https://robertlambert.org/audiopost/your-revelation-is-the-victory-part-2/',
    year: "1969",
    date: "October- 26-1969",
  },
];

export default audioSermons;
